"use client";
import {useEffect,useState} from 'react';
import AppShell from '../../components/AppShell';
import {Icon} from '../../components/Brand';
import {LoadingState,ErrorState,EmptyState} from '../../components/DataStates';
import {useSchoolContext} from '../../lib/useSchoolContext';
import {money} from '../../lib/school';
export default function Fees(){
 const {supabase,school,schoolId,role,loading,error,reload}=useSchoolContext();
 const isPortal=role==='parent'||role==='student';
 const [invoices,setInvoices]=useState([]),[students,setStudents]=useState([]),[classes,setClasses]=useState([]),[structures,setStructures]=useState([]);
 const [structureForm,setStructureForm]=useState({name:'',amount:'',class_id:''}),[showStructure,setShowStructure]=useState(false);
 const [student,setStudent]=useState(''),[amount,setAmount]=useState(''),[payInvoice,setPayInvoice]=useState(null),[payAmount,setPayAmount]=useState(''),[show,setShow]=useState(false),[notice,setNotice]=useState(''),[saving,setSaving]=useState(false);
 async function load(){if(!supabase||!schoolId)return;const [a,b,c,d]=await Promise.all([supabase.from('students').select('id,first_name,last_name').eq('school_id',schoolId).order('first_name'),supabase.from('fee_invoices').select('*,students(first_name,last_name),payments(*)').eq('school_id',schoolId).order('created_at',{ascending:false}),supabase.from('fee_structures').select('*,classes(name)').eq('school_id',schoolId).order('created_at',{ascending:false}),supabase.from('classes').select('id,name').eq('school_id',schoolId).order('name')]);for(const r of [a,b,c,d])if(r.error)throw r.error;setStudents(a.data||[]);setInvoices(b.data||[]);setStructures(c.data||[]);setClasses(d.data||[])}
 useEffect(()=>{load().catch(e=>setNotice(e.message))},[supabase,schoolId]);
 async function addStructure(e){e.preventDefault();try{const {error}=await supabase.from('fee_structures').insert({school_id:schoolId,name:structureForm.name,amount:Number(structureForm.amount),class_id:structureForm.class_id||null});if(error)throw error;setStructureForm({name:'',amount:'',class_id:''});setShowStructure(false);await load()}catch(e){setNotice(e.message)}}
 async function add(e){e.preventDefault();setSaving(true);try{const {error}=await supabase.from('fee_invoices').insert({school_id:schoolId,student_id:student,amount:Number(amount)});if(error)throw error;setAmount('');setStudent('');setShow(false);await load()}catch(e){setNotice(e.message)}finally{setSaving(false)}}
 async function record(e){e.preventDefault();setSaving(true);try{const invoice=payInvoice;const value=Number(payAmount);if(!value||value>Number(invoice.amount)-Number(invoice.amount_paid||0))throw new Error('Enter a valid amount not greater than the invoice balance.');const {error}=await supabase.from('payments').insert({school_id:schoolId,student_id:invoice.student_id,invoice_id:invoice.id,amount:value,provider:'manual',payment_method:'cash_or_transfer',status:'successful',paid_at:new Date().toISOString()});if(error)throw error;const paid=Math.min(Number(invoice.amount),Number(invoice.amount_paid||0)+value);const u=await supabase.from('fee_invoices').update({amount_paid:paid,status:paid>=Number(invoice.amount)?'paid':'partially_paid'}).eq('id',invoice.id).eq('school_id',schoolId);if(u.error)throw u.error;setPayInvoice(null);setPayAmount('');await load()}catch(e){setNotice(e.message)}finally{setSaving(false)}}
 async function online(id){try{const r=await fetch('/api/payments/paystack',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({invoice_id:id})});const j=await r.json();if(!r.ok)throw new Error(j.error);window.location.assign(j.authorization_url)}catch(e){setNotice(e.message)}}
 if(loading)return <LoadingState label="Loading fees…"/>;if(error)return <ErrorState message={error} onRetry={reload}/>;
 const outstanding=invoices.reduce((a,i)=>a+Math.max(0,Number(i.amount)-Number(i.amount_paid||0)),0),collected=invoices.reduce((a,i)=>a+Number(i.amount_paid||0),0);
 return <AppShell active="Fees & payments" schoolName={school?.name} role={role}>
  <div className="app-page-head"><div><h1>Fees & payments</h1><p>{isPortal?'View your linked school invoices and pay outstanding balances.':'Issue invoices, manage fee structures, record offline payments and collect online through Paystack.'}</p></div>{!isPortal&&<button className="app-button primary" onClick={()=>setShow(!show)}><Icon name="plus" size={15}/> Create invoice</button>}</div>
  {notice&&<div className="notice">{notice}</div>}
  {!isPortal&&show&&<div className="app-panel" style={{marginBottom:14}}><div className="app-panel-head"><h2>Create invoice</h2></div><form onSubmit={add} className="data-form"><div className="form-label"><label>Student</label><select required value={student} onChange={e=>setStudent(e.target.value)}><option value="">Select student</option>{students.map(s=><option key={s.id} value={s.id}>{s.first_name} {s.last_name}</option>)}</select></div><div className="form-label"><label>Amount</label><input type="number" min="1" required value={amount} onChange={e=>setAmount(e.target.value)}/></div><div className="form-actions"><button type="button" className="app-button" onClick={()=>setShow(false)}>Cancel</button><button className="app-button primary" disabled={saving}>{saving?'Creating…':'Create invoice'}</button></div></form></div>}
  {!isPortal&&payInvoice&&<div className="app-panel" style={{marginBottom:14}}><div className="app-panel-head"><h2>Record payment</h2><span>Balance: {money(Number(payInvoice.amount)-Number(payInvoice.amount_paid||0),school?.currency||'NGN')}</span></div><form onSubmit={record} className="data-form"><div className="form-label"><label>Amount received</label><input type="number" min="1" value={payAmount} onChange={e=>setPayAmount(e.target.value)}/></div><div className="form-actions"><button type="button" className="app-button" onClick={()=>setPayInvoice(null)}>Cancel</button><button className="app-button primary" disabled={saving}>{saving?'Saving…':'Record payment'}</button></div></form></div>}
  {!isPortal&&<div className="app-panel" style={{marginBottom:14}}><div className="app-panel-head"><h2>Fee structures</h2><button className="app-button" onClick={()=>setShowStructure(!showStructure)}>Add structure</button></div>{showStructure&&<form onSubmit={addStructure} className="data-form" style={{marginBottom:12}}><div className="form-label"><label>Name</label><input required value={structureForm.name} onChange={e=>setStructureForm({...structureForm,name:e.target.value})}/></div><div className="form-label"><label>Amount</label><input required type="number" min="0" value={structureForm.amount} onChange={e=>setStructureForm({...structureForm,amount:e.target.value})}/></div><div className="form-label"><label>Class</label><select value={structureForm.class_id} onChange={e=>setStructureForm({...structureForm,class_id:e.target.value})}><option value="">All classes</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="form-actions"><button className="app-button primary">Save structure</button></div></form>}<div className="tag-list">{structures.map(x=><span className="tag" key={x.id}>{x.name} · {money(x.amount,school?.currency||'NGN')}</span>)}</div></div>}
  <div className="app-grid-4"><div className="app-stat"><small>Invoices</small><strong>{invoices.length}</strong><em>Recorded</em></div><div className="app-stat"><small>Outstanding</small><strong>{money(outstanding,school?.currency||'NGN')}</strong><em>Needs attention</em></div><div className="app-stat"><small>Collected</small><strong>{money(collected,school?.currency||'NGN')}</strong><em>Paid to date</em></div><div className="app-stat"><small>Students</small><strong>{students.length}</strong><em>Available for invoicing</em></div></div>
  <div className="app-panel" style={{marginTop:14}}><div className="app-panel-head"><h2>Invoices</h2><span>Recent first</span></div><div className="app-table-wrap"><table className="app-table"><thead><tr><th>Student</th><th>Amount</th><th>Paid</th><th>Balance</th><th>Status</th><th>Actions</th></tr></thead><tbody>{invoices.length?invoices.map(i=>{const bal=Math.max(0,Number(i.amount)-Number(i.amount_paid||0));return <tr key={i.id}><td><strong>{i.students?.first_name} {i.students?.last_name}</strong></td><td>{money(i.amount,school?.currency||'NGN')}</td><td>{money(i.amount_paid,school?.currency||'NGN')}</td><td>{money(bal,school?.currency||'NGN')}</td><td><span className={`status ${bal?'warn':'good'}`}>{bal?'Outstanding':'Paid'}</span></td><td><div className="table-actions">{bal>0&&(isPortal?<button className="app-button primary" onClick={()=>online(i.id)}>Pay online</button>:<><button className="app-button" onClick={()=>{setPayInvoice(i);setPayAmount('')}}>Record</button><button className="app-button primary" onClick={()=>online(i.id)}>Pay online</button></>)}</div></td></tr>}) : <tr><td colSpan="6"><EmptyState title="No invoices yet" description="There are no invoices visible for this account."/></td></tr>}</tbody></table></div></div>
 </AppShell>
}
