"use client";
import {useEffect,useState} from 'react';
import AppShell from '../../components/AppShell';
import {LoadingState,ErrorState,EmptyState} from '../../components/DataStates';

export default function Student(){
 const [loading,setLoading]=useState(true),[error,setError]=useState(''),[ctx,setCtx]=useState(null),[student,setStudent]=useState(null),[exams,setExams]=useState([]),[results,setResults]=useState([]),[attendance,setAttendance]=useState([]),[assignments,setAssignments]=useState([]),[notice,setNotice]=useState('');
 async function load(){try{const {getCurrentContext}=await import('../../lib/school');const c=await getCurrentContext();setCtx(c);const {supabase,schoolId,user}=c;const {data:link,error:lerr}=await supabase.from('student_accounts').select('student_id').eq('school_id',schoolId).eq('user_id',user.id).maybeSingle();if(lerr)throw lerr;if(!link)throw new Error('No student account is linked to this login.');const [s,e,r,a,as]=await Promise.all([supabase.from('students').select('*,classes(name)').eq('school_id',schoolId).eq('id',link.student_id).single(),supabase.from('cbt_exams').select('*,classes(name),subjects(name)').eq('school_id',schoolId).in('status',['scheduled','live']),supabase.from('student_term_results').select('*,academic_sessions(name),academic_terms(name),subjects(name)').eq('school_id',schoolId).eq('student_id',link.student_id).in('status',['published','locked']).order('updated_at',{ascending:false}).limit(50),supabase.from('attendance_records').select('*').eq('school_id',schoolId).eq('student_id',link.student_id).order('attendance_date',{ascending:false}).limit(20),supabase.from('assignments').select('*,classes(name),subjects(name)').eq('school_id',schoolId).eq('class_id',null).eq('status','published')]);
  if(s.data?.class_id){const {data:classAssignments,error:ae}=await supabase.from('assignments').select('*,classes(name),subjects(name)').eq('school_id',schoolId).eq('class_id',s.data.class_id).eq('status','published').order('due_at');if(ae)throw ae;setAssignments(classAssignments||[])} else setAssignments(as.data||[]);
  for(const x of [s,e,r,a,as])if(x.error)throw x.error;setStudent(s.data);setExams(e.data||[]);setResults(r.data||[]);setAttendance(a.data||[])}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function submitAssignment(a){const content=window.prompt(`Your response for “${a.title}”\n\nYou can submit a written response now. File attachments can be added in a later workflow.`);if(content===null)return;if(!content.trim()){setNotice('Please enter a response before submitting.');return}try{const {supabase,schoolId,user}=ctx;const {error}=await supabase.from('assignment_submissions').upsert({school_id:schoolId,assignment_id:a.id,student_id:student.id,status:'submitted',submitted_at:new Date().toISOString(),content:content.trim()},{onConflict:'assignment_id,student_id'});if(error)throw error;setNotice('Assignment submitted successfully.');await load()}catch(e){setNotice(e.message)}}
 if(loading)return <LoadingState label="Loading student portal…"/>;if(error)return <AppShell active="Overview" schoolName={ctx?.school?.name} role="Student"><ErrorState message={error}/></AppShell>;
 return <AppShell active="Overview" schoolName={ctx?.school?.name} role="Student"><div className="app-page-head"><div><h1>Student portal</h1><p>{student?.first_name} {student?.last_name} · {student?.classes?.name||'Class not assigned'}</p></div></div>{notice&&<div className="notice success">{notice}</div>}<div className="app-grid-4"><div className="app-stat"><small>Attendance</small><strong>{attendance.length?Math.round(attendance.filter(x=>x.status==='present').length/attendance.length*100):0}%</strong><em>Recent records</em></div><div className="app-stat"><small>Results</small><strong>{results.length}</strong><em>Released results</em></div><div className="app-stat"><small>CBT</small><strong>{exams.length}</strong><em>Available exams</em></div><div className="app-stat"><small>Admission</small><strong>{student?.admission_number||'-'}</strong><em>Student record</em></div></div><div className="app-content-grid" style={{marginTop:14}}><div className="app-panel"><div className="app-panel-head"><h2>Assignments</h2><span>{assignments.length}</span></div>{assignments.length?<div className="stack-list">{assignments.map(a=><AssignmentItem key={a.id} assignment={a} schoolId={ctx.schoolId} studentId={student.id} onSubmit={submitAssignment}/>)}</div>:<EmptyState title="No assignments yet" description="Published assignments for your class will appear here."/>}</div><div className="app-panel"><div className="app-panel-head"><h2>Available CBT exams</h2></div><div className="stack-list">{exams.length?exams.map(e=><div className="list-select" key={e.id}><span><strong>{e.title}</strong><small>{e.subjects?.name||'Subject'} · {e.duration_minutes} minutes</small></span><a className="app-button primary" href={`/student/cbt/${e.id}`}>Start</a></div>):<EmptyState title="No exams available"/>}</div></div></div><div className="app-panel" style={{marginTop:14}}><div className="app-panel-head"><div><h2>Released academic results</h2><span>Results appear here only after publication and parent review.</span></div></div><div className="stack-list">{results.length?results.map(r=><div className="list-select" key={r.id}><span><strong>{r.subjects?.name||'Subject'}</strong><small>{r.academic_sessions?.name||'Session'} · {r.academic_terms?.name||'Term'} · {r.grade||'—'}</small></span><b>{Number(r.total||0).toFixed(1)}</b></div>):<EmptyState title="No released results yet" description="Your parent must review a published result before it is opened here."/>}</div></div></AppShell>
}
function AssignmentItem({assignment,schoolId,studentId,onSubmit}){const [submission,setSubmission]=useState(null);useEffect(()=>{let alive=true;(async()=>{const {createClient}=await import('../../lib/supabase');const s=createClient();const {data}=await s.from('assignment_submissions').select('*').eq('school_id',schoolId).eq('assignment_id',assignment.id).eq('student_id',studentId).maybeSingle();if(alive)setSubmission(data)})();return()=>{alive=false}},[assignment.id,schoolId,studentId]);const late=assignment.due_at&&new Date(assignment.due_at)<new Date()&&!submission;return <div className="list-select" style={{alignItems:'flex-start'}}><span><strong>{assignment.title}</strong><small>{assignment.subjects?.name||'Subject'} · Due {assignment.due_at?new Date(assignment.due_at).toLocaleString():'No date'} · {assignment.max_score||100} pts</small>{submission?.score!=null&&<small>Score: {submission.score}/{assignment.max_score||100}{submission.feedback?` · ${submission.feedback}`:''}</small>}</span>{submission?.status?<span className="status good">{submission.status==='returned'?`${submission.score??'-'} / ${assignment.max_score||100}`:'Submitted'}</span>:<button className="app-button primary" onClick={()=>onSubmit(assignment)}>{late?'Submit late':'Submit'}</button>}</div>}
