"use client";
import {useEffect,useState} from 'react';
import AppShell from '../../components/AppShell';
import {LoadingState,ErrorState,EmptyState} from '../../components/DataStates';
import {useSchoolContext} from '../../lib/useSchoolContext';
export default function Grading(){
 const {supabase,school,schoolId,role,loading,error,reload}=useSchoolContext();const [scales,setScales]=useState([]),[selected,setSelected]=useState(null),[form,setForm]=useState({grade:'',min_score:'',max_score:'',remark:'',grade_point:''}),[notice,setNotice]=useState('');
 async function load(){if(!supabase||!schoolId)return;const {data,error}=await supabase.from('grading_scales').select('*,grading_scale_items(*)').eq('school_id',schoolId).order('name');if(error)throw error;setScales(data||[]);if(!selected&&data?.[0])setSelected(data[0])}useEffect(()=>{load().catch(e=>setNotice(e.message))},[supabase,schoolId]);
 async function add(e){e.preventDefault();if(!selected)return;const {error}=await supabase.from('grading_scale_items').insert({...form,school_id:schoolId,scale_id:selected.id,min_score:Number(form.min_score),max_score:Number(form.max_score),grade_point:form.grade_point?Number(form.grade_point):null});if(error)setNotice(error.message);else{setForm({grade:'',min_score:'',max_score:'',remark:'',grade_point:''});await load()}}
 if(loading)return <LoadingState label="Loading grading scales…"/>;if(error)return <ErrorState message={error} onRetry={reload}/>;return <AppShell active="Grading" schoolName={school?.name} role={role}><div className="app-page-head"><div><h1>Grading configuration</h1><p>Configure the grading scale used by report cards and score calculations.</p></div></div>{notice&&<div className="notice">{notice}</div>}<div className="app-content-grid"><div className="app-panel"><div className="app-panel-head"><h2>Scales</h2><span>{scales.length}</span></div><div className="stack-list">{scales.map(s=><button className={`list-select ${selected?.id===s.id?'selected':''}`} key={s.id} onClick={()=>setSelected(s)}><span><strong>{s.name}</strong><small>{s.is_default?'Default':''}</small></span><b>{s.grading_scale_items?.length||0}</b></button>)}</div></div><div className="app-panel"><div className="app-panel-head"><h2>{selected?.name||'Select a scale'}</h2></div>{selected?<><form onSubmit={add} className="data-form"><div className="form-label"><label>Grade</label><input required value={form.grade} onChange={e=>setForm({...form,grade:e.target.value.toUpperCase()})}/></div><div className="form-label"><label>Min score</label><input type="number" min="0" max="100" required value={form.min_score} onChange={e=>setForm({...form,min_score:e.target.value})}/></div><div className="form-label"><label>Max score</label><input type="number" min="0" max="100" required value={form.max_score} onChange={e=>setForm({...form,max_score:e.target.value})}/></div><div className="form-label"><label>Grade point</label><input type="number" min="0" value={form.grade_point} onChange={e=>setForm({...form,grade_point:e.target.value})}/></div><div className="form-label full"><label>Remark</label><input value={form.remark} onChange={e=>setForm({...form,remark:e.target.value})}/></div><div className="form-actions"><button className="app-button primary">Add grade</button></div></form><div className="stack-list" style={{marginTop:15}}>{(selected.grading_scale_items||[]).map(i=><div className="list-select" key={i.id}><span><strong>{i.grade}</strong><small>{i.min_score} - {i.max_score} · {i.remark}</small></span><b>{i.grade_point??'-'}</b></div>)}</div></>:<EmptyState title="Select a grading scale"/>}</div></div></AppShell>
}
