import { NextResponse } from 'next/server';
import { createServerSupabase } from '../../../../lib/supabase-server';
export async function POST(req){
 try{
  const supabase=createServerSupabase();const {data:{user}}=await supabase.auth.getUser();if(!user)return NextResponse.json({error:'Unauthorized'},{status:401});
  const body=await req.json();const {invoice_id}=body;const idempotencyKey=req.headers.get('idempotency-key')||body.idempotency_key||`${user.id}:${invoice_id}:${Math.floor(Date.now()/60000)}`;if(!invoice_id)return NextResponse.json({error:'Invoice is required.'},{status:400});
  const {data:i,error:ie}=await supabase.from('fee_invoices').select('id,school_id,amount,amount_paid,student_id,students(first_name,last_name)').eq('id',invoice_id).single();if(ie)throw ie;
  const {data:m}=await supabase.from('school_memberships').select('school_id,role,schools(currency)').eq('user_id',user.id).eq('school_id',i.school_id).eq('status','active').maybeSingle();
  let authorized=Boolean(m&&['owner','admin','bursar'].includes(m.role));
  if(!authorized){const [g,a]=await Promise.all([supabase.from('student_guardians').select('id').eq('school_id',i.school_id).eq('student_id',i.student_id).eq('user_id',user.id).maybeSingle(),supabase.from('student_accounts').select('id').eq('school_id',i.school_id).eq('student_id',i.student_id).eq('user_id',user.id).eq('status','active').maybeSingle()]);authorized=Boolean(g.data||a.data)}
  if(!authorized)return NextResponse.json({error:'You are not authorized to pay this invoice.'},{status:403});
  const balance=Math.max(0,Number(i.amount)-Number(i.amount_paid||0));if(!balance)return NextResponse.json({error:'Invoice is already paid.'},{status:400});if(!process.env.PAYSTACK_SECRET_KEY)return NextResponse.json({error:'Paystack is not configured.'},{status:503});
  const serviceKey=process.env.SUPABASE_SERVICE_ROLE_KEY;
  if(serviceKey){const {createClient}=await import('@supabase/supabase-js');const admin=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL,serviceKey,{auth:{autoRefreshToken:false,persistSession:false}});const {data:existing}=await admin.from('payment_idempotency_keys').select('response,status').eq('school_id',i.school_id).eq('idempotency_key',idempotencyKey).maybeSingle();if(existing?.response?.authorization_url)return NextResponse.json(existing.response);await admin.from('payment_idempotency_keys').upsert({school_id:i.school_id,idempotency_key:idempotencyKey,provider:'paystack',status:'processing'},{onConflict:'school_id,idempotency_key'});}
  const reference=`edvora_fee_${invoice_id}_${Date.now()}`;const response=await fetch('https://api.paystack.co/transaction/initialize',{method:'POST',headers:{Authorization:`Bearer ${process.env.PAYSTACK_SECRET_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({email:user.email,amount:Math.round(balance*100),reference,metadata:{school_id:i.school_id,invoice_id,student_id:i.student_id,kind:'school_fee'}})});const json=await response.json();if(!response.ok||!json.status){if(serviceKey){const {createClient}=await import('@supabase/supabase-js');const admin=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL,serviceKey,{auth:{autoRefreshToken:false,persistSession:false}});await admin.from('payment_idempotency_keys').update({status:'failed',response:{error:json.message||'Payment initialization failed.'},completed_at:new Date().toISOString()}).eq('school_id',i.school_id).eq('idempotency_key',idempotencyKey)}return NextResponse.json({error:json.message||'Payment initialization failed.'},{status:502});}const result={authorization_url:json.data.authorization_url,reference:json.data.reference};if(serviceKey){const {createClient}=await import('@supabase/supabase-js');const admin=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL,serviceKey,{auth:{autoRefreshToken:false,persistSession:false}});await admin.from('payment_idempotency_keys').update({status:'completed',response:result,completed_at:new Date().toISOString()}).eq('school_id',i.school_id).eq('idempotency_key',idempotencyKey)}return NextResponse.json(result);
 }catch(e){return NextResponse.json({error:e.message||'Payment initialization failed.'},{status:500})}
}
