import crypto from 'crypto';
import { NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';
export async function POST(req){
 const raw=await req.text();const signature=req.headers.get('x-paystack-signature')||'';if(!process.env.PAYSTACK_SECRET_KEY||!signature)return NextResponse.json({error:'Webhook not configured'},{status:400});
 const expected=crypto.createHmac('sha512',process.env.PAYSTACK_SECRET_KEY).update(raw).digest('hex');if(expected.length!==signature.length||!crypto.timingSafeEqual(Buffer.from(expected),Buffer.from(signature)))return NextResponse.json({error:'Invalid signature'},{status:401});
 let event;try{event=JSON.parse(raw)}catch{return NextResponse.json({error:'Invalid JSON'},{status:400})}
 const data=event.data||{};const meta=data.metadata||{};const service=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.SUPABASE_SERVICE_ROLE_KEY,{auth:{autoRefreshToken:false,persistSession:false}});
 if(data.id){const {data:existing}=await service.from('subscription_events').select('id').eq('provider_event_id',String(data.id)).maybeSingle();if(existing)return NextResponse.json({received:true,duplicate:true})}
 let schoolId=meta.school_id||null;
 if(!schoolId&&(data.subscription?.subscription_code||data.subscription_code)){const {data:sub}=await service.from('subscriptions').select('school_id').eq('provider_subscription_id',data.subscription?.subscription_code||data.subscription_code).maybeSingle();schoolId=sub?.school_id||null}
 if(!schoolId&&data.customer?.customer_code){const {data:sub}=await service.from('subscriptions').select('school_id').eq('provider_customer_id',data.customer.customer_code).maybeSingle();schoolId=sub?.school_id||null}
 if(event.event==='charge.success'&&meta.kind==='edvora_subscription'&&schoolId){const plan=meta.plan_code||'starter';const cycle=meta.cycle||'monthly';const periodDays=cycle==='yearly'?365:30;await service.from('subscriptions').upsert({school_id:schoolId,plan_code:plan,status:'active',provider:'paystack',provider_customer_id:data.customer?.customer_code||null,provider_subscription_id:data.subscription?.subscription_code||null,authorization_code:data.authorization?.authorization_code||null,email:data.customer?.email||null,billing_cycle:cycle,current_period_start:new Date().toISOString(),current_period_end:new Date(Date.now()+periodDays*86400000).toISOString(),updated_at:new Date().toISOString()},{onConflict:'school_id'})}
 if(['subscription.create','subscription.not_renew','subscription.disable','invoice.payment_failed','invoice.create'].includes(event.event)&&schoolId){const status=event.event==='invoice.payment_failed'?'past_due':event.event==='subscription.disable'?'cancelled':'active';await service.from('subscriptions').update({status,cancel_at_period_end:event.event==='subscription.not_renew',provider_subscription_id:data.subscription_code||data.subscription?.subscription_code||null,updated_at:new Date().toISOString()}).eq('school_id',schoolId)}
 if(event.event==='charge.success'&&meta.invoice_id&&schoolId){const amount=Number(data.amount||0)/100;const {data:invoice}=await service.from('fee_invoices').select('id,amount,amount_paid,student_id').eq('id',meta.invoice_id).eq('school_id',schoolId).maybeSingle();if(invoice&&amount>0&&amount<=Number(invoice.amount)-Number(invoice.amount_paid||0)){const {data:already}=await service.from('payments').select('id').eq('provider','paystack').eq('provider_reference',data.reference).maybeSingle();if(!already){const paid=Math.min(Number(invoice.amount),Number(invoice.amount_paid||0)+amount);await service.from('payments').insert({school_id:schoolId,student_id:invoice.student_id,invoice_id:invoice.id,amount,provider:'paystack',provider_reference:data.reference,status:'successful',paid_at:new Date().toISOString(),metadata:event});await service.from('fee_invoices').update({amount_paid:paid,status:paid>=Number(invoice.amount)?'paid':'partially_paid',updated_at:new Date().toISOString()}).eq('id',invoice.id).eq('school_id',schoolId)}}}
 if(data.id&&schoolId)await service.from('subscription_events').insert({school_id:schoolId,provider:'paystack',event_type:event.event,provider_event_id:String(data.id),payload:event,processed_at:new Date().toISOString()});
 return NextResponse.json({received:true});
}
