"use client";
import {useEffect,useState} from 'react';
import AppShell from '../../components/AppShell';
import {LoadingState,ErrorState,EmptyState} from '../../components/DataStates';
import {useSchoolContext} from '../../lib/useSchoolContext';
export default function Admissions(){
 const {supabase,school,schoolId,role,loading,error,reload}=useSchoolContext();const [items,setItems]=useState([]),[classes,setClasses]=useState([]),[form,setForm]=useState({first_name:'',last_name:'',email:'',phone:'',desired_class_id:'',notes:''}),[show,setShow]=useState(false),[notice,setNotice]=useState(''),[saving,setSaving]=useState(false);
 async function load(){if(!supabase||!schoolId)return;const [a,c]=await Promise.all([supabase.from('admission_applications').select('*,classes(name)').eq('school_id',schoolId).order('created_at',{ascending:false}),supabase.from('classes').select('*').eq('school_id',schoolId).order('name')]);if(a.error)throw a.error;if(c.error)throw c.error;setItems(a.data||[]);setClasses(c.data||[])}useEffect(()=>{load().catch(e=>setNotice(e.message))},[supabase,schoolId]);
 async function add(e){e.preventDefault();setSaving(true);try{const {error}=await supabase.from('admission_applications').insert({...form,school_id:schoolId,desired_class_id:form.desired_class_id||null,source:'staff'});if(error)throw error;setForm({first_name:'',last_name:'',email:'',phone:'',desired_class_id:'',notes:''});setShow(false);await load()}catch(e){setNotice(e.message)}finally{setSaving(false)}}
 async function status(id,status){const {error}=await supabase.from('admission_applications').update({status,updated_at:new Date().toISOString()}).eq('id',id).eq('school_id',schoolId);if(error)setNotice(error.message);else load()}
 async function enroll(a){setSaving(true);try{const {data:st,error:se}=await supabase.from('students').insert({school_id:schoolId,first_name:a.first_name,last_name:a.last_name,class_id:a.desired_class_id||null,status:'active',date_of_birth:a.date_of_birth||null,gender:a.gender||null}).select().single();if(se)throw se;const {data:{user}}=await supabase.auth.getUser();await supabase.from('student_enrollments').insert({school_id:schoolId,student_id:st.id,class_id:a.desired_class_id||null,is_current:true});await supabase.from('student_lifecycle_events').insert({school_id:schoolId,student_id:st.id,event_type:'admitted',to_class_id:a.desired_class_id||null,created_by:user.id,notes:`Enrolled from ${a.application_number}`});await supabase.from('admission_applications').update({status:'enrolled',updated_at:new Date().toISOString()}).eq('id',a.id);setNotice(`${a.first_name} ${a.last_name} is now a student.`);await load()}catch(e){setNotice(e.message)}finally{setSaving(false)}}
 if(loading)return <LoadingState label="Loading admissions…"/>;if(error)return <ErrorState message={error} onRetry={reload}/>;return <AppShell active="Admissions" schoolName={school?.name} role={role}><div className="app-page-head"><div><h1>Admissions</h1><p>Track applicants from submission through admission and enrollment.</p></div><button className="app-button primary" onClick={()=>setShow(!show)}>New application</button></div>{notice&&<div className="notice">{notice}</div>}{show&&<div className="app-panel" style={{marginBottom:14}}><form onSubmit={add} className="data-form"><div className="form-label"><label>First name</label><input required value={form.first_name} onChange={e=>setForm({...form,first_name:e.target.value})}/></div><div className="form-label"><label>Last name</label><input required value={form.last_name} onChange={e=>setForm({...form,last_name:e.target.value})}/></div><div className="form-label"><label>Email</label><input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></div><div className="form-label"><label>Phone</label><input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></div><div className="form-label"><label>Desired class</label><select value={form.desired_class_id} onChange={e=>setForm({...form,desired_class_id:e.target.value})}><option value="">Select</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="form-label full"><label>Notes</label><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></div><div className="form-actions"><button type="button" className="app-button" onClick={()=>setShow(false)}>Cancel</button><button className="app-button primary" disabled={saving}>{saving?'Saving…':'Create application'}</button></div></form></div>}<div className="app-panel"><div className="app-panel-head"><h2>Applications</h2><span>{items.length}</span></div><div className="app-table-wrap"><table className="app-table"><thead><tr><th>Applicant</th><th>Application</th><th>Class</th><th>Status</th><th>Update</th></tr></thead><tbody>{items.length?items.map(a=><tr key={a.id}><td><strong>{a.first_name} {a.last_name}</strong><br/><small>{a.email||a.phone||''}</small></td><td>{a.application_number}</td><td>{a.classes?.name||'-'}</td><td><span className="status warn">{a.status}</span></td><td><div className="table-actions">{a.status==='accepted'&&<button className="app-button primary" disabled={saving} onClick={()=>enroll(a)}>Enroll</button>}<select value={a.status} onChange={e=>status(a.id,e.target.value)}><option>submitted</option><option>review</option><option>accepted</option><option>rejected</option><option>enrolled</option></select></div></td></tr>):<tr><td colSpan="5"><EmptyState title="No applications yet"/></td></tr>}</tbody></table></div></div></AppShell>
}
