import fs from 'node:fs';import path from 'node:path';
const root=process.cwd();
const required=['app/page.js','app/not-found.js','app/error.js','app/loading.js','app/school/[slug]/page.js','app/school/[slug]/apply/page.js','app/operations/page.js','app/observability/page.js','app/data-governance/page.js','app/imports/page.js','app/integrations/page.js','app/super-admin/page.js','app/api/super-admin/route.js','app/api/contact/route.js','app/api/public-admissions/route.js','app/api/notifications/route.js','supabase/EDVORA_COMPLETE_SCHEMA_V16.sql','supabase/EDVORA_V17_PRODUCTION_UPGRADE.sql','supabase/EDVORA_V17_SECURITY_TESTS.sql'];
for(const f of required)if(!fs.existsSync(path.join(root,f)))throw new Error(`Missing ${f}`);
const js=[];function walk(d){for(const e of fs.readdirSync(d,{withFileTypes:true})){if(['node_modules','.next','.git'].includes(e.name))continue;const p=path.join(d,e.name);if(e.isDirectory())walk(p);else if(e.name.endsWith('.js')&&!p.includes('public/'))js.push(p)}}walk(root);
let checked=0;for(const f of js){const s=fs.readFileSync(f,'utf8');if((s.match(/[{}]/g)||[]).length%2!==0)throw new Error(`Suspicious brace count: ${f}`);checked++}
const css=fs.readFileSync(path.join(root,'app/globals.css'),'utf8');if(/Inter/.test(css)||/Plus Jakarta Sans/.test(css))throw new Error('Legacy typography remains in globals.css');if(/gradient\s*\(/i.test(css))throw new Error('Gradient CSS remains');if(/backdrop-filter/.test(css))throw new Error('Glassmorphism/backdrop filter remains');
const sql=fs.readFileSync(path.join(root,'supabase/EDVORA_COMPLETE_SCHEMA_V16.sql'),'utf8');const executableSql=sql.replace(/--.*$/gm,'');if(/gen_random_bytes\s*\(/.test(executableSql))throw new Error('Unsupported gen_random_bytes usage');if(!sql.includes('teacher_user_id=auth.uid()'))throw new Error('Teacher assignment policy is not teacher-scoped');
const up=fs.readFileSync(path.join(root,'supabase/EDVORA_V17_PRODUCTION_UPGRADE.sql'),'utf8');for(const needle of ['supabase_realtime','notification_deliveries','backup_operations','capture_school_health'])if(!up.includes(needle))throw new Error(`V17 upgrade missing ${needle}`);
console.log(`Edvora V17 production checks passed: ${required.length} critical files; ${checked} JS files inspected.`);
