"use client";
import {useEffect,useState} from 'react';
import AppShell from '../../components/AppShell';
import {LoadingState,ErrorState} from '../../components/DataStates';
import {useSchoolContext} from '../../lib/useSchoolContext';
import {money} from '../../lib/school';
export default function Reports(){
 const {supabase,school,schoolId,role,loading,error,reload}=useSchoolContext();const [data,setData]=useState({students:0,teachers:0,classes:0,invoices:0,outstanding:0,paid:0,attendance:0,assessments:0,cbt:0}),[classes,setClasses]=useState([]),[sessions,setSessions]=useState([]),[filters,setFilters]=useState({class_id:'',session_id:''}),[notice,setNotice]=useState('');
 async function load(){if(!supabase||!schoolId)return;const [c,s]=await Promise.all([supabase.from('classes').select('id,name').eq('school_id',schoolId).order('name'),supabase.from('academic_sessions').select('id,name').eq('school_id',schoolId).order('starts_on',{ascending:false})]);if(c.error)throw c.error;if(s.error)throw s.error;setClasses(c.data||[]);setSessions(s.data||[]);let studentQ=supabase.from('students').select('id',{count:'exact',head:true}).eq('school_id',schoolId);if(filters.class_id)studentQ=studentQ.eq('class_id',filters.class_id);const [st,t,cl,i,a,ass,cbt]=await Promise.all([studentQ,supabase.from('staff_profiles').select('id',{count:'exact',head:true}).eq('school_id',schoolId).eq('staff_type','teacher'),supabase.from('classes').select('id',{count:'exact',head:true}).eq('school_id',schoolId),supabase.from('fee_invoices').select('amount,amount_paid').eq('school_id',schoolId),supabase.from('attendance_records').select('status').eq('school_id',schoolId),supabase.from('assessments').select('id',{count:'exact',head:true}).eq('school_id',schoolId),supabase.from('cbt_exams').select('id',{count:'exact',head:true}).eq('school_id',schoolId)]);for(const r of [st,t,cl,i,a,ass,cbt])if(r.error)throw r.error;const invoices=i.data||[],attendance=a.data||[];const present=attendance.filter(x=>x.status==='present').length;setData({students:st.count||0,teachers:t.count||0,classes:cl.count||0,invoices:invoices.length,outstanding:invoices.reduce((n,x)=>n+Math.max(0,Number(x.amount)-Number(x.amount_paid||0)),0),paid:invoices.reduce((n,x)=>n+Number(x.amount_paid||0),0),attendance:attendance.length?Math.round((present/attendance.length)*100):0,assessments:ass.count||0,cbt:cbt.count||0})}
 useEffect(()=>{load().catch(e=>setNotice(e.message))},[supabase,schoolId,filters.class_id,filters.session_id]);
 if(loading)return <LoadingState label="Building reports…"/>;if(error)return <ErrorState message={error} onRetry={reload}/>;const csv=`Metric,Value\nStudents,${data.students}\nTeachers,${data.teachers}\nClasses,${data.classes}\nInvoices,${data.invoices}\nOutstanding,${data.outstanding}\nCollected,${data.paid}\nAttendance rate,${data.attendance}%\nAssessments,${data.assessments}\nCBT exams,${data.cbt}`;function download(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='edvora-school-report.csv';a.click();URL.revokeObjectURL(a.href)}
 return <AppShell active="Reports" schoolName={school?.name} role={role}><div className="app-page-head"><div><h1>Reports</h1><p>Live operational, academic and finance summaries.</p></div><div className="app-head-actions"><button className="app-button" onClick={()=>window.print()}>Print</button><button className="app-button primary" onClick={download}>Export CSV</button></div></div>{notice&&<div className="notice error">{notice}</div>}<div className="app-panel" style={{marginBottom:14}}><div className="data-form"><div className="form-label"><label>Class filter</label><select value={filters.class_id} onChange={e=>setFilters({...filters,class_id:e.target.value})}><option value="">All classes</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="form-label"><label>Session</label><select value={filters.session_id} onChange={e=>setFilters({...filters,session_id:e.target.value})}><option value="">All sessions</option>{sessions.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div></div></div><div className="app-grid-4"><div className="app-stat"><small>Students</small><strong>{data.students}</strong><em>Active register</em></div><div className="app-stat"><small>Teachers</small><strong>{data.teachers}</strong><em>Teaching team</em></div><div className="app-stat"><small>Attendance</small><strong>{data.attendance}%</strong><em>Recorded attendance</em></div><div className="app-stat"><small>Outstanding</small><strong>{money(data.outstanding,school?.currency||'NGN')}</strong><em>Invoice balance</em></div></div><div className="app-content-grid" style={{marginTop:14}}><div className="app-panel"><div className="app-panel-head"><h2>Finance summary</h2><span>Live</span></div><div className="report-row"><span>Invoices</span><strong>{data.invoices}</strong></div><div className="report-row"><span>Collected</span><strong>{money(data.paid,school?.currency||'NGN')}</strong></div><div className="report-row"><span>Outstanding</span><strong>{money(data.outstanding,school?.currency||'NGN')}</strong></div></div><div className="app-panel"><div className="app-panel-head"><h2>Academic summary</h2><span>Live</span></div><div className="report-row"><span>Assessments</span><strong>{data.assessments}</strong></div><div className="report-row"><span>CBT exams</span><strong>{data.cbt}</strong></div><div className="report-row"><span>Classes</span><strong>{data.classes}</strong></div></div></div></AppShell>
}
