"use client";
import {useEffect,useState} from 'react';
import AppShell from '../../components/AppShell';
import {LoadingState,ErrorState,EmptyState} from '../../components/DataStates';
import {useSchoolContext} from '../../lib/useSchoolContext';
export default function Promotion(){
 const {supabase,school,schoolId,role,loading,error,reload}=useSchoolContext();const [classes,setClasses]=useState([]),[students,setStudents]=useState([]),[fromClass,setFromClass]=useState(''),[toClass,setToClass]=useState(''),[session,setSession]=useState(''),[sessions,setSessions]=useState([]),[selected,setSelected]=useState({}),[notice,setNotice]=useState(''),[saving,setSaving]=useState(false);
 async function load(){if(!supabase||!schoolId)return;const [c,s,a]=await Promise.all([supabase.from('classes').select('*').eq('school_id',schoolId).order('name'),supabase.from('students').select('*').eq('school_id',schoolId).eq('status','active').order('first_name'),supabase.from('academic_sessions').select('*').eq('school_id',schoolId).order('starts_on',{ascending:false})]);for(const x of [c,s,a])if(x.error)throw x.error;setClasses(c.data||[]);setStudents(s.data||[]);setSessions(a.data||[]);if(!session&&a.data?.[0])setSession(a.data[0].id)}useEffect(()=>{load().catch(e=>setNotice(e.message))},[supabase,schoolId]);
 const roster=students.filter(s=>s.class_id===fromClass);
 async function process(){if(!fromClass||!toClass||fromClass===toClass||!session||!roster.length){setNotice('Select different source and destination classes, a session, and at least one student.');return}setSaving(true);try{const {data:{user}}=await supabase.auth.getUser();const {data:b,error:be}=await supabase.from('promotion_batches').insert({school_id:schoolId,session_id:session,from_class_id:fromClass,to_class_id:toClass,status:'draft',created_by:user.id}).select().single();if(be)throw be;const chosen=roster.filter(s=>selected[s.id]!==false);const {error:ie}=await supabase.from('promotion_items').insert(chosen.map(s=>({school_id:schoolId,batch_id:b.id,student_id:s.id,old_class_id:fromClass,new_class_id:toClass,status:'promoted'})));if(ie)throw ie;for(const s of chosen){const {error:u}=await supabase.from('student_enrollments').update({is_current:false,ended_on:new Date().toISOString().slice(0,10)}).eq('school_id',schoolId).eq('student_id',s.id).eq('is_current',true);await supabase.from('student_enrollments').insert({school_id:schoolId,student_id:s.id,class_id:toClass,session_id:session,is_current:true});await supabase.from('students').update({class_id:toClass,updated_at:new Date().toISOString()}).eq('id',s.id).eq('school_id',schoolId);if(u)throw u;await supabase.from('student_lifecycle_events').insert({school_id:schoolId,student_id:s.id,event_type:'promoted',from_class_id:fromClass,to_class_id:toClass,session_id:session,created_by:user.id})}await supabase.from('promotion_batches').update({status:'processed'}).eq('id',b.id);setNotice(`Promoted ${chosen.length} students.`);await load()}catch(e){setNotice(e.message)}finally{setSaving(false)}}
 if(loading)return <LoadingState label="Loading promotion…"/>;if(error)return <ErrorState message={error} onRetry={reload}/>;return <AppShell active="Promotion" schoolName={school?.name} role={role}><div className="app-page-head"><div><h1>Student promotion</h1><p>Move students between classes with an auditable promotion history.</p></div></div>{notice&&<div className="notice">{notice}</div>}<div className="app-panel"><div className="data-form"><div className="form-label"><label>Session</label><select value={session} onChange={e=>setSession(e.target.value)}><option value="">Select</option>{sessions.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div><div className="form-label"><label>From class</label><select value={fromClass} onChange={e=>{setFromClass(e.target.value);setSelected({})}}><option value="">Select</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="form-label"><label>To class</label><select value={toClass} onChange={e=>setToClass(e.target.value)}><option value="">Select</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div></div></div><div className="app-panel" style={{marginTop:14}}><div className="app-panel-head"><h2>Students</h2><span>{roster.length} in source class</span></div>{roster.length?<div className="stack-list">{roster.map(s=><label className="list-select" key={s.id}><span><strong>{s.first_name} {s.last_name}</strong><small>{s.admission_number||'No admission number'}</small></span><input type="checkbox" checked={selected[s.id]!==false} onChange={e=>setSelected({...selected,[s.id]:e.target.checked})}/></label>)}<div className="form-actions" style={{marginTop:12}}><button className="app-button primary" onClick={process} disabled={saving}>{saving?'Processing…':'Promote selected students'}</button></div></div>:<EmptyState title="Select a source class" description="Students in the selected class will appear here."/>}</div></AppShell>
}
