"use client";
import {useEffect,useState} from 'react';
import AppShell from '../../components/AppShell';
import {Icon} from '../../components/Brand';
import {LoadingState,ErrorState,EmptyState} from '../../components/DataStates';
import {useSchoolContext} from '../../lib/useSchoolContext';

export default function Teachers(){
 const {supabase,school,schoolId,role,loading,error,reload}=useSchoolContext();
 const [staff,setStaff]=useState([]),[classes,setClasses]=useState([]),[subjects,setSubjects]=useState([]),[show,setShow]=useState(false),[showInvite,setShowInvite]=useState(false),[invite,setInvite]=useState({email:'',role:'teacher'}),[form,setForm]=useState({full_name:'',email:'',phone:'',employee_number:'',department:''}),[saving,setSaving]=useState(false),[notice,setNotice]=useState('');
 async function load(){if(!supabase||!schoolId)return;const [s,c,sub]=await Promise.all([supabase.from('staff_profiles').select('*').eq('school_id',schoolId).eq('staff_type','teacher').order('created_at',{ascending:false}),supabase.from('classes').select('*').eq('school_id',schoolId).order('name'),supabase.from('subjects').select('*').eq('school_id',schoolId).order('name')]);if(s.error)throw s.error;setStaff(s.data||[]);setClasses(c.data||[]);setSubjects(sub.data||[])}
 useEffect(()=>{load().catch(e=>setNotice(e.message))},[supabase,schoolId]);
 async function sendInvite(e){e.preventDefault();setSaving(true);setNotice('');try{const r=await fetch('/api/invitations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...invite,school_id:schoolId})});const j=await r.json();if(!r.ok)throw new Error(j.error);setShowInvite(false);setInvite({email:'',role:'teacher'});setNotice(j.emailed?'Invitation email sent.':'Invitation created. Add Resend settings to send email automatically. Link: '+j.link)}catch(e){setNotice(e.message)}finally{setSaving(false)}}
 async function add(e){e.preventDefault();setSaving(true);setNotice('');try{const r=await fetch('/api/staff/teacher',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,school_id:schoolId})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Unable to add teacher.');setForm({full_name:'',email:'',phone:'',employee_number:'',department:''});setShow(false);setNotice(j.invitation?.emailed?'Teacher profile created and invitation email sent.':j.invitation?.link?`Teacher profile created. Invitation link: ${j.invitation.link}`:'Teacher profile created. Add an email and invite the teacher when you are ready.');await load()}catch(e){setNotice(e.message)}finally{setSaving(false)}}
 async function assignTeacher(staffId,kind,value){const teacher=staff.find(x=>x.id===staffId);if(!teacher?.user_id){setNotice('This teacher profile is not linked to a user account yet. Create/accept an invitation first.');return}const table=kind==='class'?'teacher_class_assignments':'teacher_subject_assignments';const payload=kind==='class'?{school_id:schoolId,teacher_user_id:teacher.user_id,class_id:value}:{school_id:schoolId,teacher_user_id:teacher.user_id,subject_id:value};const {error}=await supabase.from(table).upsert(payload,{onConflict:kind==='class'?'school_id,teacher_user_id,class_id':'school_id,teacher_user_id,subject_id,class_id'});if(error)setNotice(error.message);else setNotice('Assignment saved.')}
 if(loading)return <LoadingState label="Loading teachers…"/>;
 if(error)return <ErrorState message={error} onRetry={reload}/>;
 return <AppShell active="Teachers" schoolName={school?.name} role={role}>
  <div className="app-page-head"><div><h1>Teachers & staff</h1><p>Manage staff profiles, invitations and teaching assignments.</p></div><div className="app-head-actions"><button className="app-button" onClick={()=>setShowInvite(!showInvite)}>Invite staff</button><button className="app-button primary" onClick={()=>setShow(!show)}><Icon name="plus" size={15}/> Add teacher</button></div></div>
  {notice&&<div className="notice error">{notice}</div>}{showInvite&&<div className="app-panel" style={{marginBottom:14}}><div className="app-panel-head"><h2>Invite a team member</h2><span>Invitation expires in 7 days</span></div><form onSubmit={sendInvite} className="data-form"><div className="form-label"><label>Email</label><input type="email" required value={invite.email} onChange={e=>setInvite({...invite,email:e.target.value})}/></div><div className="form-label"><label>Role</label><select value={invite.role} onChange={e=>setInvite({...invite,role:e.target.value})}><option value="teacher">Teacher</option><option value="admin">Admin</option><option value="bursar">Bursar</option><option value="staff">Staff</option></select></div><div className="form-actions"><button type="button" className="app-button" onClick={()=>setShowInvite(false)}>Cancel</button><button className="app-button primary" disabled={saving}>{saving?'Sending…':'Create invitation'}</button></div></form></div>}
  {show&&<div className="app-panel" style={{marginBottom:14}}><div className="app-panel-head"><h2>Teacher profile</h2><span>Include an email to create an invitation automatically</span></div><form onSubmit={add} className="data-form"><div className="form-label"><label>Full name</label><input required value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})}/></div><div className="form-label"><label>Email</label><input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></div><div className="form-label"><label>Phone</label><input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></div><div className="form-label"><label>Employee number</label><input value={form.employee_number} onChange={e=>setForm({...form,employee_number:e.target.value})}/></div><div className="form-label"><label>Department</label><input value={form.department} onChange={e=>setForm({...form,department:e.target.value})}/></div><div className="form-actions"><button type="button" className="app-button" onClick={()=>setShow(false)}>Cancel</button><button className="app-button primary" disabled={saving}>{saving?'Saving…':'Create teacher'}</button></div></form></div>}
  <div className="app-panel"><div className="app-panel-head"><h2>Teaching team</h2><span>{staff.length} profiles · invite status shown below</span></div><div className="app-table-wrap"><table className="app-table"><thead><tr><th>Teacher</th><th>Email</th><th>Employee no.</th><th>Department</th><th>Status</th></tr></thead><tbody>{staff.length?staff.map(t=><tr key={t.id}><td><strong>{t.full_name}</strong></td><td>{t.email||'-'}</td><td>{t.employee_number||'-'}</td><td>{t.department||'-'}</td><td><span className={`status ${t.status==='active'?'good':'warn'}`}>{t.status}</span></td></tr>):<tr><td colSpan="5"><EmptyState title="No teachers yet" description="Create staff profiles here, then link them to user accounts and assignments." action={<button className="app-button primary" onClick={()=>setShow(true)}>Add teacher</button>}/></td></tr>}</tbody></table></div></div>
  {staff.length>0&&<div className="app-content-grid" style={{marginTop:14}}><div className="app-panel"><div className="app-panel-head"><h2>Class assignment</h2><span>Admin only</span></div><div className="assignment-list">{staff.slice(0,8).map(t=><div className="assignment-row" key={t.id}><strong>{t.full_name}</strong><select defaultValue="" onChange={e=>e.target.value&&assignTeacher(t.id,'class',e.target.value)}><option value="">Assign a class…</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div>)}</div></div><div className="app-panel"><div className="app-panel-head"><h2>Subject assignment</h2><span>Admin only</span></div><div className="assignment-list">{staff.slice(0,8).map(t=><div className="assignment-row" key={t.id}><strong>{t.full_name}</strong><select defaultValue="" onChange={e=>e.target.value&&assignTeacher(t.id,'subject',e.target.value)}><option value="">Assign a subject…</option>{subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div>)}</div></div></div>}
 </AppShell>
}
