"use client";
import {useEffect,useMemo,useState} from 'react';import AppShell from '../../components/AppShell';import {createClient} from '../../lib/supabase';
export default function SuperAdmin(){const [ok,setOk]=useState(false),[schools,setSchools]=useState([]),[incidents,setIncidents]=useState([]),[flags,setFlags]=useState([]),[query,setQuery]=useState(''),[status,setStatus]=useState('all'),[error,setError]=useState(''),[saving,setSaving]=useState('');
 async function load(){const s=createClient();const {data:{user}}=await s.auth.getUser();const {data:p}=await s.from('platform_admins').select('user_id').eq('user_id',user?.id).maybeSingle();if(!p){setError('Platform administrator access is required.');return}setOk(true);const [a,b,c]=await Promise.all([s.from('schools').select('id,name,status,school_type,created_at,timezone').order('created_at',{ascending:false}),s.from('system_incidents').select('*').order('created_at',{ascending:false}),s.from('platform_feature_flags').select('*').order('feature_key')]);setSchools(a.data||[]);setIncidents(b.data||[]);setFlags(c.data||[])}
 useEffect(()=>{load().catch(e=>setError(e.message))},[]);
 const filtered=useMemo(()=>schools.filter(x=>(status==='all'||x.status===status)&&(!query||x.name.toLowerCase().includes(query.toLowerCase()))),[schools,query,status]);
 async function changeStatus(id,next){setSaving(id);setError('');try{const r=await fetch('/api/super-admin',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({schoolId:id,status:next})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Update failed');await load()}catch(e){setError(e.message)}finally{setSaving('')}}
 if(error&&!ok)return <AppShell active="Super Admin" role="Platform admin"><div className="notice error">{error}</div></AppShell>;if(!ok)return <AppShell active="Super Admin" role="Platform admin"><div className="loading-block">Loading platform controls…</div></AppShell>;
 return <AppShell active="Super Admin" role="Platform admin"><div className="app-page-head"><div><h1>Platform control</h1><p>Manage tenants, incidents, feature access and platform operations.</p></div></div>{error&&<div className="notice error">{error}</div>}<div className="stats-grid"><div className="stat-card"><small>Total schools</small><strong>{schools.length}</strong></div><div className="stat-card"><small>Active tenants</small><strong>{schools.filter(x=>x.status==='active'||x.status==='trialing').length}</strong></div><div className="stat-card"><small>Open incidents</small><strong>{incidents.filter(x=>x.status!=='resolved').length}</strong></div><div className="stat-card"><small>Feature flags</small><strong>{flags.length}</strong></div></div><section className="app-panel"><div className="app-panel-head"><h2>Schools</h2><span>{filtered.length} shown</span></div><div className="toolbar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search schools" aria-label="Search schools"/><select value={status} onChange={e=>setStatus(e.target.value)} aria-label="Filter by status"><option value="all">All statuses</option><option value="active">Active</option><option value="trialing">Trialing</option><option value="suspended">Suspended</option><option value="cancelled">Cancelled</option></select></div><div className="school-admin-list">{filtered.map(x=><div className="data-row" key={x.id}><div><strong>{x.name}</strong><small>{x.school_type} · {x.timezone} · joined {new Date(x.created_at).toLocaleDateString()}</small></div><div className="row-actions"><span className={`status ${x.status==='suspended'||x.status==='cancelled'?'alert':'good'}`}>{x.status}</span><select value={x.status} disabled={saving===x.id} onChange={e=>changeStatus(x.id,e.target.value)} aria-label={`Change ${x.name} status`}><option value="active">Active</option><option value="trialing">Trialing</option><option value="suspended">Suspended</option><option value="cancelled">Cancelled</option></select></div></div>)}{!filtered.length&&<div className="empty-state">No schools match this filter.</div>}</div></section><div className="split-grid" style={{marginTop:14}}><section className="app-panel"><h2>System incidents</h2>{incidents.length?incidents.map(x=><div className="data-row" key={x.id}><div><strong>{x.title}</strong><small>{x.severity} · {x.status}</small></div></div>):<div className="empty-state">No incidents.</div>}</section><section className="app-panel"><h2>Feature flags</h2>{flags.length?flags.map(x=><div className="data-row" key={x.id}><div><strong>{x.feature_key}</strong><small>{x.enabled?'Enabled':'Disabled'}</small></div></div>):<div className="empty-state">No feature flags.</div>}</section></div></AppShell>}
