"use client";
import {useEffect,useState} from 'react';
import AppShell from '../../components/AppShell';
import {LoadingState,ErrorState,EmptyState} from '../../components/DataStates';
import {useSchoolContext} from '../../lib/useSchoolContext';
export default function Communications(){
 const {supabase,school,schoolId,role,loading,error,reload}=useSchoolContext();const [items,setItems]=useState([]),[threads,setThreads]=useState([]),[members,setMembers]=useState([]),[show,setShow]=useState(false),[showMessage,setShowMessage]=useState(false),[form,setForm]=useState({title:'',body:'',audience:'all'}),[message,setMessage]=useState({subject:'',recipient:'' ,body:''}),[notice,setNotice]=useState(''),[saving,setSaving]=useState(false),[selectedThread,setSelectedThread]=useState(null),[threadMessages,setThreadMessages]=useState([]);
 async function load(){if(!supabase||!schoolId)return;const [a,t,m]=await Promise.all([supabase.from('announcements').select('*').eq('school_id',schoolId).order('created_at',{ascending:false}),supabase.from('message_threads').select('*,message_participants(user_id)').eq('school_id',schoolId).order('created_at',{ascending:false}),supabase.from('school_memberships').select('user_id,role').eq('school_id',schoolId).eq('status','active')]);if(a.error)throw a.error;if(t.error)throw t.error;setItems(a.data||[]);setThreads(t.data||[]);setMembers(m.data||[])}
 useEffect(()=>{load().catch(e=>setNotice(e.message))},[supabase,schoolId]);
 async function add(e){e.preventDefault();setSaving(true);try{const {data:{user}}=await supabase.auth.getUser();const {error}=await supabase.from('announcements').insert({...form,school_id:schoolId,created_by:user.id});if(error)throw error;setForm({title:'',body:'',audience:'all'});setShow(false);await load()}catch(e){setNotice(e.message)}finally{setSaving(false)}}
 async function createMessage(e){e.preventDefault();setSaving(true);try{const {data:{user}}=await supabase.auth.getUser();if(!message.recipient)throw new Error('Select a recipient.');const {data:t,error:te}=await supabase.from('message_threads').insert({school_id:schoolId,subject:message.subject,created_by:user.id}).select().single();if(te)throw te;const {error:pe}=await supabase.from('message_participants').insert([{school_id:schoolId,thread_id:t.id,user_id:user.id},{school_id:schoolId,thread_id:t.id,user_id:message.recipient}]);if(pe)throw pe;const {error:me}=await supabase.from('messages').insert({school_id:schoolId,thread_id:t.id,sender_user_id:user.id,body:message.body});if(me)throw me;setMessage({subject:'',recipient:'',body:''});setShowMessage(false);await load()}catch(e){setNotice(e.message)}finally{setSaving(false)}}
 async function openThread(t){setSelectedThread(t);const {data,error}=await supabase.from('messages').select('*').eq('school_id',schoolId).eq('thread_id',t.id).order('created_at');if(error)setNotice(error.message);else setThreadMessages(data||[])}
 if(loading)return <LoadingState label="Loading communications…"/>;if(error)return <ErrorState message={error} onRetry={reload}/>;return <AppShell active="Messages" schoolName={school?.name} role={role}><div className="app-page-head"><div><h1>Communications</h1><p>Announcements, direct messages and notifications with school-scoped access.</p></div><div className="app-head-actions"><button className="app-button" onClick={()=>setShowMessage(!showMessage)}>New message</button><button className="app-button primary" onClick={()=>setShow(!show)}>New announcement</button></div></div>{notice&&<div className="notice">{notice}</div>}{show&&<div className="app-panel" style={{marginBottom:14}}><form onSubmit={add} className="data-form"><div className="form-label full"><label>Title</label><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></div><div className="form-label"><label>Audience</label><select value={form.audience} onChange={e=>setForm({...form,audience:e.target.value})}><option value="all">Everyone</option><option value="teachers">Teachers</option><option value="parents">Parents</option><option value="students">Students</option><option value="staff">Staff</option></select></div><div className="form-label full"><label>Message</label><textarea required rows="5" value={form.body} onChange={e=>setForm({...form,body:e.target.value})}/></div><div className="form-actions"><button type="button" className="app-button" onClick={()=>setShow(false)}>Cancel</button><button className="app-button primary" disabled={saving}>Publish</button></div></form></div>}{showMessage&&<div className="app-panel" style={{marginBottom:14}}><form onSubmit={createMessage} className="data-form"><div className="form-label full"><label>Subject</label><input required value={message.subject} onChange={e=>setMessage({...message,subject:e.target.value})}/></div><div className="form-label full"><label>Recipient</label><select required value={message.recipient} onChange={e=>setMessage({...message,recipient:e.target.value})}><option value="">Select school member</option>{members.filter(m=>m.user_id).map(m=><option key={m.user_id} value={m.user_id}>{m.role} · {m.user_id}</option>)}</select></div><div className="form-label full"><label>Message</label><textarea required rows="5" value={message.body} onChange={e=>setMessage({...message,body:e.target.value})}/></div><div className="form-actions"><button type="button" className="app-button" onClick={()=>setShowMessage(false)}>Cancel</button><button className="app-button primary" disabled={saving}>Send message</button></div></form></div>}
 <div className="app-content-grid"><div className="app-panel"><div className="app-panel-head"><h2>Announcements</h2><span>{items.length}</span></div><div className="announcement-list">{items.length?items.map(a=><article className="announcement-card" key={a.id}><span className="status good">{a.audience}</span><h3>{a.title}</h3><p>{a.body}</p><small>{new Date(a.created_at).toLocaleString()}</small></article>):<EmptyState title="No announcements"/>}</div></div><div className="app-panel"><div className="app-panel-head"><h2>Messages</h2><span>{threads.length}</span></div><div className="stack-list">{threads.length?threads.map(t=><button className="list-select" key={t.id} onClick={()=>openThread(t)}><span><strong>{t.subject}</strong><small>{new Date(t.created_at).toLocaleString()}</small></span><span>Open</span></button>):<EmptyState title="No message threads"/>}</div>{selectedThread&&<div className="stack-list" style={{marginTop:14}}>{threadMessages.map(m=><div className="announcement-card" key={m.id}><small>{m.sender_user_id}</small><p>{m.body}</p></div>)}</div>}</div></div></AppShell>
}
