import Link from 'next/link';
import MarketingNav from '../components/MarketingNav';
import {Icon,Logo} from '../components/Brand';

const heroImage='https://images.pexels.com/photos/31118300/pexels-photo-31118300.jpeg?cs=srgb&dl=pexels-sam-the-shuttersmith-513212544-31118300.jpg&fm=jpg';

function DashboardMock(){return <div className="hero-product-wrap">
 <div className="product-window">
  <div className="product-window-bar"><div className="window-dots"><i/><i/><i/></div><span>Edvora Admin</span><div className="window-search">Search</div></div>
  <div className="mock-body">
   <aside className="mock-side"><div className="mock-logo"><span className="logo-mark"><b/><b/><b/></span><strong>Edvora</strong></div><div className="mock-nav active"><Icon name="home" size={14}/> Overview</div><div className="mock-nav"><Icon name="users" size={14}/> Students</div><div className="mock-nav"><Icon name="class" size={14}/> Classes</div><div className="mock-nav"><Icon name="clipboard" size={14}/> CBT</div><div className="mock-nav"><Icon name="wallet" size={14}/> Fees</div></aside>
   <div className="mock-main"><div className="mock-heading"><div><small>School overview</small><h3>Good morning, Admin</h3></div><span className="mock-chip">This term</span></div>
    <div className="mock-stats"><div><span className="mini-accent blue"/><small>Students</small><strong>1,248</strong><em>+12%</em></div><div><span className="mini-accent lime"/><small>Teachers</small><strong>96</strong><em>+2%</em></div><div><span className="mini-accent yellow"/><small>Attendance</small><strong>96%</strong><em>+2.4%</em></div><div><span className="mini-accent coral"/><small>Outstanding</small><strong>₦4.8m</strong><em>12 due</em></div></div>
    <div className="mock-lower"><div className="mock-panel chart-panel"><div className="mock-panel-head"><strong>Student progress</strong><small>Jan – Jun</small></div><div className="chart"><span/><span/><span/><span/><span/><span/><span/></div></div><div className="mock-panel activity-panel"><div className="mock-panel-head"><strong>Today's activity</strong><small>View all</small></div><div className="activity-row"><b className="activity-dot blue"/><span>New student enrolled</span><small>2h</small></div><div className="activity-row"><b className="activity-dot lime"/><span>Results published</span><small>4h</small></div><div className="activity-row"><b className="activity-dot yellow"/><span>Parent payment</span><small>6h</small></div></div></div>
   </div>
  </div>
 </div>
 <div className="hero-shape shape-blue"/><div className="hero-shape shape-lime"/><div className="hero-shape shape-yellow"/><div className="hero-shape shape-coral"/>
 </div>}

function SectionIntro({eyebrow,title,children,center=false}){return <div className={`section-intro ${center?'center':''}`}><div className="section-kicker">{eyebrow}</div><h2>{title}</h2><p>{children}</p></div>}

export default function Home(){
 return <div className="marketing-site"><MarketingNav/>
  <main>
   <section className="hero-v2"><div className="hero-grid-v2"><div className="hero-copy"><div className="hero-kicker"><span className="kicker-dot"/> Smart infrastructure for modern schools.</div><h1>Everything your school needs.<br/><span>One platform.</span></h1><p>Edvora connects administration, academics, examinations, communication and payments in one modern school operating system.</p><div className="hero-actions"><Link className="button-primary" href="/signup">Get Started <Icon name="arrow" size={17}/></Link><a className="button-secondary" href="#features">Explore Edvora <Icon name="arrow" size={17}/></a></div><div className="hero-note"><span className="note-check"><Icon name="check" size={13}/></span> Built for the everyday reality of modern schools.</div></div><div className="hero-visual"><div className="hero-photo"><img src={heroImage} alt="African student in school uniform"/><div className="photo-caption"><span className="caption-mark"><b/><b/><b/></span><span>School life, connected.</span></div></div><DashboardMock/></div></div></section>

   <section className="trust-strip"><div className="trust-inner"><span>ONE CONNECTED SCHOOL</span><i/><span>ADMINISTRATION</span><i/><span>ACADEMICS</span><i/><span>ASSESSMENT</span><i/><span>COMMUNICATION</span><i/><span>PAYMENTS</span></div></section>

   <section className="section-v2 platform-section" id="features"><div className="container-v2"><SectionIntro eyebrow="One connected platform" title="The daily work, connected.">Everything your team needs to run the school sits in one organized environment. Less chasing information. Less duplicate entry. More time for the work that matters.</SectionIntro><div className="feature-grid-v2"><article className="feature-large"><div className="feature-visual blue-visual"><div className="mini-interface"><div className="mini-interface-head"><span>Students</span><small>1,248 active</small></div><div className="mini-student"><span className="avatar a1">AO</span><div><strong>Amaka Okafor</strong><small>SS2A · Active</small></div><b>96%</b></div><div className="mini-student"><span className="avatar a2">DA</span><div><strong>David Adeyemi</strong><small>JSS3B · Active</small></div><b>91%</b></div><div className="mini-student"><span className="avatar a3">YA</span><div><strong>Yusuf Ahmed</strong><small>SS1C · Active</small></div><b>88%</b></div></div></div><div className="feature-copy"><div className="feature-icon blue-icon"><Icon name="users" size={20}/></div><h3>Student records</h3><p>Admissions, classes, guardians, documents and student history in one secure record.</p><Link href="/signup">Explore student management <Icon name="arrow" size={15}/></Link></div></article>
<article className="feature-large"><div className="feature-visual lime-visual"><div className="fee-board"><div><small>Fee collection</small><strong>₦18.4m</strong></div><div className="fee-bars"><i style={{height:'42%'}}/><i style={{height:'62%'}}/><i style={{height:'54%'}}/><i style={{height:'80%'}}/><i style={{height:'72%'}}/><i style={{height:'92%'}}/></div></div></div><div className="feature-copy"><div className="feature-icon lime-icon"><Icon name="wallet" size={20}/></div><h3>Fees & payments</h3><p>Create fee structures, issue invoices, track balances and keep payment records current.</p><Link href="/signup">Explore payments <Icon name="arrow" size={15}/></Link></div></article>
<article className="feature-small"><div className="feature-icon yellow-icon"><Icon name="clipboard" size={20}/></div><h3>Results & CBT</h3><p>Move from assessment to report cards and serious computer-based testing.</p></article><article className="feature-small"><div className="feature-icon coral-icon"><Icon name="calendar" size={20}/></div><h3>Attendance</h3><p>Capture attendance quickly and see patterns that need attention.</p></article><article className="feature-small"><div className="feature-icon aqua-icon"><Icon name="message" size={20}/></div><h3>Communication</h3><p>Keep school, teacher, parent and student communication connected.</p></article></div></div></section>

   <section className="split-section navy-section" id="solutions"><div className="container-v2 split-grid"><div><div className="section-kicker light">Built around the school</div><h2>One system.<br/>Different people.<br/><span>Clearer work.</span></h2><p>Edvora adapts the experience to the people using it without fragmenting the platform. Everyone sees the work that matters to them.</p><Link className="button-light" href="/signup">Start your school <Icon name="arrow" size={17}/></Link></div><div className="role-stack"><div className="role-card role-admin"><span className="role-number">01</span><div><strong>School admin</strong><p>See the organization, manage operations and act on what needs attention.</p></div><Icon name="arrow" size={18}/></div><div className="role-card role-teacher"><span className="role-number">02</span><div><strong>Teacher</strong><p>Classes, attendance, assignments, questions, CBT and results in fewer steps.</p></div><Icon name="arrow" size={18}/></div><div className="role-card role-parent"><span className="role-number">03</span><div><strong>Parent</strong><p>See attendance, fees, assignments, announcements and your child's progress.</p></div><Icon name="arrow" size={18}/></div><div className="role-card role-student"><span className="role-number">04</span><div><strong>Student</strong><p>Timetable, assignments, examinations and results in a focused space.</p></div><Icon name="arrow" size={18}/></div></div></div></section>

   <section className="section-v2 cbt-section"><div className="container-v2"><div className="cbt-grid"><div className="cbt-visual"><div className="exam-window"><div className="exam-head"><strong>Edvora CBT</strong><span>Mathematics · SS2</span><b>42:18</b></div><div className="exam-body"><aside><small>QUESTION</small><strong>12 / 40</strong><div className="question-dots">{Array.from({length:12}).map((_,i)=><i key={i} className={i<8?'done':i===8?'current':''}>{i+1}</i>)}</div></aside><div className="question"><small>MATHEMATICS</small><h3>If 3x + 7 = 25, what is the value of x?</h3><label><span>A</span> 4</label><label className="selected"><span>B</span> 6</label><label><span>C</span> 7</label><label><span>D</span> 8</label></div></div></div></div><div className="cbt-copy"><div className="section-kicker">Edvora CBT</div><h2>Serious examination infrastructure.</h2><p>When students enter an examination, Edvora becomes quiet, focused and reliable. Question banks, randomized exams, autosave and reporting belong in one purpose-built environment.</p><div className="check-list"><span><Icon name="check" size={15}/> Question bank</span><span><Icon name="check" size={15}/> Randomized exams</span><span><Icon name="check" size={15}/> Autosave & recovery</span><span><Icon name="check" size={15}/> Exam reporting</span></div><Link className="text-link" href="/cbt">Explore CBT <Icon name="arrow" size={15}/></Link></div></div></div></section>

   <section className="section-v2 ai-section"><div className="container-v2 ai-grid"><div><div className="section-kicker">Edvora AI</div><h2>Useful intelligence, inside the workflow.</h2><p>AI should help schools do real work faster: generate questions, draft report comments, surface attendance patterns and answer authorized questions about school data.</p><Link className="button-primary" href="/signup">Build with Edvora <Icon name="arrow" size={17}/></Link></div><div className="ai-board"><div className="ai-top"><span className="ai-spark"><Icon name="spark" size={16}/></span><strong>Ask Edvora</strong><small>School data</small></div><div className="ai-prompt">Which classes have the highest outstanding fees?</div><div className="ai-answer"><span className="answer-mark"><Icon name="check" size={14}/></span><div><strong>Three classes need attention</strong><p>SS2A · ₦1.2m<br/>JSS3B · ₦940k<br/>SS1C · ₦720k</p></div></div><div className="ai-foot">Based only on data you are authorized to access.</div></div></div></section>

   <section className="section-v2 white-label-section"><div className="container-v2"><div className="brand-builder"><div className="brand-builder-copy"><div className="section-kicker">White-label experience</div><h2>Your school identity.<br/>Edvora infrastructure.</h2><p>Every school can have its own logo, colors, communications and public website while keeping the same dependable Edvora foundation.</p><Link className="text-link" href="/signup">Explore school branding <Icon name="arrow" size={15}/></Link></div><div className="brand-board"><div className="brand-browser"><div className="browser-head"><span className="mini-brand"><b/><b/><b/> Your School</span><span>Admissions</span><span>About</span><span>Contact</span></div><div className="browser-hero"><div><small>YOUR SCHOOL</small><strong>Learning that moves<br/>with every child.</strong><button>Book a school tour</button></div><div className="browser-photo"/></div></div><div className="brand-swatches"><i className="sw-blue"/><i className="sw-lime"/><i className="sw-yellow"/><i className="sw-coral"/></div></div></div></div></section>

   <section className="section-v2 audience-section"><div className="container-v2"><SectionIntro eyebrow="Made for the whole school" title="One platform. Four experiences." center>Edvora gives each person a focused experience while keeping the school connected underneath.</SectionIntro><div className="audience-grid"><Link href="/dashboard" className="audience-card"><span className="audience-num">01</span><div className="audience-icon blue-icon"><Icon name="settings" size={21}/></div><h3>School admin</h3><p>Operations, academics, people, finance and school-wide visibility.</p><span className="audience-arrow"><Icon name="arrow" size={16}/></span></Link><Link href="/teacher" className="audience-card"><span className="audience-num">02</span><div className="audience-icon lime-icon"><Icon name="clipboard" size={21}/></div><h3>Teacher</h3><p>Daily classes, attendance, assignments, questions, CBT and results.</p><span className="audience-arrow"><Icon name="arrow" size={16}/></span></Link><Link href="/parent" className="audience-card"><span className="audience-num">03</span><div className="audience-icon yellow-icon"><Icon name="users" size={21}/></div><h3>Parent</h3><p>Know how your child is doing without chasing the school for updates.</p><span className="audience-arrow"><Icon name="arrow" size={16}/></span></Link><Link href="/student" className="audience-card"><span className="audience-num">04</span><div className="audience-icon coral-icon"><Icon name="chart" size={21}/></div><h3>Student</h3><p>Everything needed for school in one focused academic space.</p><span className="audience-arrow"><Icon name="arrow" size={16}/></span></Link></div></div></section>

   <section className="pricing-section" id="pricing"><div className="container-v2"><SectionIntro eyebrow="Pricing" title="Start simple. Grow with your school." center>Plans are designed around school size and the workflows you need. Contact Edvora for current pricing and onboarding.</SectionIntro><div className="pricing-grid"><article><span>Starter</span><h3>For small schools</h3><p>Core school operations for teams getting organized.</p><div className="price-placeholder">Talk to us</div><small>Current pricing on request</small><Link href="/signup" className="price-button">Get started <Icon name="arrow" size={15}/></Link><ul><li>Student records</li><li>Classes & subjects</li><li>Attendance</li><li>Fees tracking</li></ul></article><article className="pricing-featured"><div className="plan-tag">Most flexible</div><span>Growth</span><h3>For growing schools</h3><p>More workflows connected as the school scales.</p><div className="price-placeholder">Talk to us</div><small>Current pricing on request</small><Link href="/signup" className="price-button">Get started <Icon name="arrow" size={15}/></Link><ul><li>Everything in Starter</li><li>Results & report cards</li><li>CBT & question bank</li><li>Communication</li></ul></article><article><span>Professional</span><h3>For larger schools</h3><p>Deeper operational control and advanced workflows.</p><div className="price-placeholder">Talk to us</div><small>Current pricing on request</small><Link href="/signup" className="price-button">Talk to Edvora <Icon name="arrow" size={15}/></Link><ul><li>Everything in Growth</li><li>Advanced reports</li><li>School websites</li><li>AI workflows</li></ul></article><article className="pricing-dark"><span>Enterprise</span><h3>School groups</h3><p>Custom infrastructure for complex organizations.</p><div className="price-placeholder">Let's talk</div><small>Custom implementation</small><Link href="/signup" className="price-button">Contact Edvora <Icon name="arrow" size={15}/></Link><ul><li>Enterprise controls</li><li>Advanced integrations</li><li>Dedicated support</li><li>Custom requirements</li></ul></article></div></div></section>

   <section className="final-cta"><div className="container-v2 final-cta-inner"><div><div className="section-kicker light">One connected school</div><h2>Ready to run your school from one place?</h2><p>Start with the work your team already does. Connect the rest when your school is ready.</p></div><Link href="/signup" className="button-light">Create your school <Icon name="arrow" size={17}/></Link></div></section>
  </main>
  <footer className="marketing-footer"><div className="container-v2 footer-grid"><div><Logo/><p>Smart infrastructure for modern schools.</p></div><div><strong>Product</strong><Link href="#features">Features</Link><Link href="#solutions">Solutions</Link><Link href="#pricing">Pricing</Link></div><div><strong>Company</strong><Link href="/login">Login</Link><Link href="/signup">Get started</Link><Link href="/reports">Reports</Link></div><div><strong>Experiences</strong><Link href="/teacher">Teacher</Link><Link href="/parent">Parent</Link><Link href="/student">Student</Link></div></div><div className="container-v2 footer-bottom"><span>© 2026 Edvora. All rights reserved.</span><span>Education · Connection · Progress</span></div></footer>
 </div>
}
