"use client";
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {Logo,Icon} from './Brand';
import {createClient} from '../lib/supabase';
const adminGroups=[{label:'Workspace',items:[['Overview','/dashboard','home'],['Students','/students','users'],['Teachers','/teachers','users'],['Classes','/classes','class'],['Admissions','/admissions','clipboard']]},{label:'Academics',items:[['Attendance','/attendance','calendar'],['Assignments','/assignments','clipboard'],['Calendar','/calendar','calendar'],['Results','/results','chart'],['Grading','/grading','chart'],['CBT','/cbt','clipboard'],['Timetable','/timetable','calendar'],['Promotion','/promotion','chart']]},{label:'Finance & communication',items:[['Fees & payments','/fees','wallet'],['Messages','/communications','message'],['Reports','/reports','chart'],['Analytics','/analytics','chart'],['Website','/website','home'],['Question Bank','/question-bank','clipboard'],['Imports','/imports','clipboard'],['Integrations','/integrations','settings'],['Support','/support','message'],['AI','/ai','chart'],['Operations','/operations','settings'],['Data & privacy','/data-governance','settings'],['Security','/security','settings'],['System health','/observability','chart']]},{label:'Account',items:[['Members','/members','users'],['Settings','/settings','settings'],['Billing','/pricing','wallet'],['Audit log','/audit','chart']]}];
const teacherGroups=[{label:'Teaching',items:[['Teacher home','/teacher','home'],['Attendance','/attendance','calendar'],['Assignments','/assignments','clipboard'],['Calendar','/calendar','calendar'],['Results','/results','chart'],['Grading','/grading','chart'],['CBT','/cbt','clipboard'],['Timetable','/timetable','calendar']]},{label:'Account',items:[['Profile','/profile','users']]}];
const parentGroups=[{label:'Parent portal',items:[['Parent portal','/parent','home'],['Link child','/parent-link','users'],['Fees','/fees','wallet'],['Messages','/communications','message'],['Profile','/profile','users']]}];
const studentGroups=[{label:'Student portal',items:[['Student portal','/student','home'],['CBT','/student/cbt','clipboard'],['Timetable','/timetable','calendar'],['Profile','/profile','users']]}];

export default function AppShell({children,active='Overview',schoolName='Your school',role='School admin',onLogout}){
 const [mobile,setMobile]=useState(false),[query,setQuery]=useState(''),[results,setResults]=useState([]),[notifications,setNotifications]=useState([]),[showNotifications,setShowNotifications]=useState(false),[schoolId,setSchoolId]=useState(null),[userName,setUserName]=useState('Account'),[platformAdmin,setPlatformAdmin]=useState(false);
 const normalized=String(role||'').toLowerCase();
 const baseGroups=normalized==='parent'?parentGroups:normalized==='student'?studentGroups:normalized==='teacher'?teacherGroups:adminGroups;const groups=platformAdmin?[...baseGroups,{label:'Platform',items:[['Super Admin','/super-admin','settings']]}]:baseGroups;
 useEffect(()=>{(async()=>{try{const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user)return;setUserName(user.user_metadata?.full_name||user.email?.split('@')[0]||'Account');const {data:pa}=await s.from('platform_admins').select('user_id').eq('user_id',user.id).maybeSingle();setPlatformAdmin(Boolean(pa));let sid=null;const preferredSchoolId=typeof window!=='undefined'?window.localStorage.getItem('edvora.currentSchoolId'):null;const membershipQuery=s.from('school_memberships').select('school_id').eq('user_id',user.id).eq('status','active');const {data:m}=preferredSchoolId?await membershipQuery.eq('school_id',preferredSchoolId).maybeSingle():await membershipQuery.order('created_at',{ascending:false}).limit(1).maybeSingle();sid=m?.school_id||null;if(sid&&typeof window!=='undefined')window.localStorage.setItem('edvora.currentSchoolId',sid);if(!sid){const {data:g}=await s.from('student_guardians').select('school_id').eq('user_id',user.id).limit(1).maybeSingle();sid=g?.school_id||null}if(!sid){const {data:a}=await s.from('student_accounts').select('school_id').eq('user_id',user.id).eq('status','active').limit(1).maybeSingle();sid=a?.school_id||null}if(!sid)return;setSchoolId(sid);const {data:n}=await s.from('notifications').select('*').eq('school_id',sid).eq('user_id',user.id).is('read_at',null).order('created_at',{ascending:false}).limit(6);setNotifications(n||[])}catch{}})()},[]);
 useEffect(()=>{const t=setTimeout(async()=>{if(!query.trim()||!schoolId||normalized==='parent'||normalized==='student'){setResults([]);return}const s=createClient();const [a,b,c,d,e,f,g]=await Promise.all([s.from('students').select('id,first_name,last_name').eq('school_id',schoolId).or(`first_name.ilike.%${query}%,last_name.ilike.%${query}%,admission_number.ilike.%${query}%`).limit(5),s.from('classes').select('id,name').eq('school_id',schoolId).ilike('name',`%${query}%`).limit(5),s.from('fee_invoices').select('id,title').eq('school_id',schoolId).ilike('title',`%${query}%`).limit(5),s.from('staff_profiles').select('id,full_name').eq('school_id',schoolId).ilike('full_name',`%${query}%`).limit(5),s.from('subjects').select('id,name').eq('school_id',schoolId).ilike('name',`%${query}%`).limit(5),s.from('assignments').select('id,title').eq('school_id',schoolId).ilike('title',`%${query}%`).limit(5),s.from('school_events').select('id,title').eq('school_id',schoolId).ilike('title',`%${query}%`).limit(5)]);setResults([...(a.data||[]).map(x=>({type:'Student',label:`${x.first_name} ${x.last_name}`,href:'/students'})),...(b.data||[]).map(x=>({type:'Class',label:x.name,href:'/classes'})),...(c.data||[]).map(x=>({type:'Invoice',label:x.title,href:'/fees'})),...(d.data||[]).map(x=>({type:'Staff',label:x.full_name,href:'/teachers'})),...(e.data||[]).map(x=>({type:'Subject',label:x.name,href:'/classes'})),...(f.data||[]).map(x=>({type:'Assignment',label:x.title,href:'/assignments'})),...(g.data||[]).map(x=>({type:'Event',label:x.title,href:'/calendar'}))]);},250);return()=>clearTimeout(t)},[query,schoolId,normalized]);
 async function markNotificationsRead(){if(!schoolId||!notifications.length)return;const s=createClient();await s.from('notifications').update({read_at:new Date().toISOString()}).in('id',notifications.map(n=>n.id));setNotifications([])}
 async function handleLogout(){try{if(onLogout){await onLogout();return}await createClient().auth.signOut()}finally{window.location.assign('/login')}}
 return <div className="app-shell-v2"><aside className={`app-sidebar ${mobile?'mobile-open':''}`}><div className="sidebar-top"><Logo/><button className="sidebar-close" onClick={()=>setMobile(false)} aria-label="Close navigation"><Icon name="close" size={20}/></button></div><div className="school-switch"><span className="school-avatar">{schoolName?.slice(0,1)||'E'}</span><span><strong>{schoolName}</strong><small>{role}</small></span></div><div className="side-nav">{groups.map(g=><div className="side-group" key={g.label}><div className="side-label">{g.label}</div>{g.items.map(([label,href,icon])=><Link key={label} href={href} className={`side-link-v2 ${active===label?'active':''}`} onClick={()=>setMobile(false)}><span className="side-icon"><Icon name={icon} size={18}/></span><span>{label}</span></Link>)}</div>)}</div><div className="sidebar-bottom"><Link href="/" className="back-site"><span>←</span> Public website</Link></div></aside><div className="app-content-v2"><header className="app-topbar-v2"><button className="mobile-nav-trigger" onClick={()=>setMobile(true)} aria-label="Open navigation"><Icon name="menu" size={22}/></button><div className="topbar-search"><Icon name="search" size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search students, classes, payments…" aria-label="Search"/>{results.length>0&&<div className="global-search-results">{results.map((r,i)=><Link href={r.href} key={i} onClick={()=>setQuery('')}><small>{r.type}</small><strong>{r.label}</strong></Link>)}</div>}</div><div className="topbar-actions"><div className="notification-wrap"><button className="icon-button" aria-label="Notifications" onClick={()=>setShowNotifications(!showNotifications)}><Icon name="message" size={19}/>{notifications.length>0&&<span className="notification-dot"/>}</button>{showNotifications&&<div className="notification-popover"><div className="popover-head"><strong>Notifications</strong><button onClick={markNotificationsRead}>Mark read</button></div>{notifications.length?notifications.map(n=><div className="notification-item" key={n.id}><strong>{n.title}</strong><small>{n.body}</small></div>):<div className="notification-empty">You're all caught up.</div>}</div>}</div><div className="profile-pill"><span className="profile-avatar">{userName.slice(0,1).toUpperCase()}</span><span className="profile-copy"><strong>{userName}</strong><small>{role}</small></span></div><button className="logout-button" onClick={handleLogout}>Log out</button></div></header><main className="app-main-v2">{children}</main></div></div>
}
