"use client";
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {createClient} from '../../lib/supabase';
import {Logo} from '../../components/Brand';
export default function ParentLink(){
 const [code,setCode]=useState(''),[relationship,setRelationship]=useState('Parent'),[status,setStatus]=useState(''),[busy,setBusy]=useState(false);useEffect(()=>{try{const saved=sessionStorage.getItem('edvora_parent_link_code');if(saved){setCode(saved);sessionStorage.removeItem('edvora_parent_link_code')}}catch{}},[]);
 async function submit(e){e.preventDefault();setBusy(true);setStatus('');try{const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user){try{sessionStorage.setItem('edvora_parent_link_code',code.trim())}catch{}window.location.assign('/login?next=/parent-link');return}const {data,error}=await s.rpc('link_parent_by_code',{link_code:code.trim(),relationship_name:relationship});if(error)throw error;setStatus(`Linked to ${data.student_name}. Redirecting to the parent portal…`);setTimeout(()=>window.location.assign('/parent'),500)}catch(e){setStatus(e.message||'Parent ID could not be linked.')}finally{setBusy(false)}}
 return <main className="auth-page"><div className="auth-card"><Logo/><h1>Link your child</h1><p>Enter the secure Parent ID supplied by your child's school. The ID is unique to one student and one school.</p>{status&&<div className={`notice ${status.includes('Linked')?'success':'error'}`}>{status}</div>}<form onSubmit={submit} className="data-form"><div className="form-label full"><label>Parent ID</label><input required minLength="20" autoComplete="off" spellCheck="false" value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="EDV-…"/></div><div className="form-label full"><label>Relationship</label><select value={relationship} onChange={e=>setRelationship(e.target.value)}><option>Parent</option><option>Mother</option><option>Father</option><option>Guardian</option><option>Caregiver</option></select></div><div className="form-actions"><button className="app-button primary" disabled={busy}>{busy?'Linking…':'Link child'}</button></div></form><p style={{marginTop:18}}>Need an account? <Link href="/signup">Create one</Link>. Already signed in? <Link href="/parent">Open parent portal</Link>.</p></div></main>
}
