"use client";
import {useEffect,useState} from 'react';
import AppShell from '../../components/AppShell';
import {LoadingState,ErrorState,EmptyState} from '../../components/DataStates';
import {useSchoolContext} from '../../lib/useSchoolContext';
export default function Members(){
 const {supabase,school,schoolId,role,loading,error,reload}=useSchoolContext();const [members,setMembers]=useState([]),[invitations,setInvitations]=useState([]),[notice,setNotice]=useState(''),[busy,setBusy]=useState('');
 async function load(){if(!supabase||!schoolId)return;const [m,i]=await Promise.all([supabase.from('school_memberships').select('id,user_id,role,status,created_at').eq('school_id',schoolId).order('created_at'),supabase.from('school_invitations').select('id,email,role,expires_at,accepted_at,created_at').eq('school_id',schoolId).order('created_at',{ascending:false})]);if(m.error)throw m.error;if(i.error)throw i.error;setMembers(m.data||[]);setInvitations(i.data||[])}
 useEffect(()=>{load().catch(e=>setNotice(e.message))},[supabase,schoolId]);
 async function suspend(id){setBusy(id);const {error}=await supabase.from('school_memberships').update({status:'suspended',updated_at:new Date().toISOString()}).eq('id',id).eq('school_id',schoolId);if(error)setNotice(error.message);else await load();setBusy('')}
 if(loading)return <LoadingState label="Loading members…"/>;if(error)return <ErrorState message={error} onRetry={reload}/>;return <AppShell active="Members" schoolName={school?.name} role={role}><div className="app-page-head"><div><h1>School members</h1><p>Review active staff, roles and invitations.</p></div></div>{notice&&<div className="notice">{notice}</div>}<div className="app-panel"><div className="app-panel-head"><h2>Members</h2><span>{members.length}</span></div><div className="app-table-wrap"><table className="app-table"><thead><tr><th>Role</th><th>User</th><th>Status</th><th>Joined</th><th>Action</th></tr></thead><tbody>{members.length?members.map(m=><tr key={m.id}><td><strong>{m.role}</strong></td><td>{m.user_id}</td><td><span className={`status ${m.status==='active'?'good':'warn'}`}>{m.status}</span></td><td>{new Date(m.created_at).toLocaleDateString()}</td><td>{m.role!=='owner'&&m.status==='active'&&<button className="app-button" disabled={busy===m.id} onClick={()=>suspend(m.id)}>{busy===m.id?'Saving…':'Suspend'}</button>}</td></tr>):<tr><td colSpan="5"><EmptyState title="No members"/></td></tr>}</tbody></table></div></div><div className="app-panel" style={{marginTop:14}}><div className="app-panel-head"><h2>Invitations</h2><span>{invitations.filter(i=>!i.accepted_at).length} pending</span></div><div className="stack-list">{invitations.length?invitations.map(i=><div className="list-select" key={i.id}><span><strong>{i.email}</strong><small>{i.role} · expires {new Date(i.expires_at).toLocaleDateString()}</small></span><span className={`status ${i.accepted_at?'good':'warn'}`}>{i.accepted_at?'Accepted':'Pending'}</span></div>):<EmptyState title="No invitations"/>}</div></div></AppShell>
}
