"use client";
import {useEffect,useState} from 'react';
import AppShell from '../../components/AppShell';
import {useSchoolContext} from '../../lib/useSchoolContext';
export default function DataGovernance(){const {supabase,school,schoolId,role,loading}=useSchoolContext();const [exports,setExports]=useState([]),[deletions,setDeletions]=useState([]),[consents,setConsents]=useState([]),[retention,setRetention]=useState([]),[notice,setNotice]=useState('');
 async function load(){if(!supabase||!schoolId)return;const [a,b,c,d]=await Promise.all([supabase.from('data_exports').select('*').eq('school_id',schoolId).order('created_at',{ascending:false}).limit(20),supabase.from('deletion_requests').select('*').eq('school_id',schoolId).order('created_at',{ascending:false}).limit(20),supabase.from('consent_records').select('*').eq('school_id',schoolId).order('created_at',{ascending:false}).limit(20),supabase.from('retention_policies').select('*').eq('school_id',schoolId).order('data_type')]);setExports(a.data||[]);setDeletions(b.data||[]);setConsents(c.data||[]);setRetention(d.data||[])}
 useEffect(()=>{load().catch(e=>setNotice(e.message))},[supabase,schoolId]);
 async function requestExport(){const {data:{user}}=await supabase.auth.getUser();const {error}=await supabase.from('data_exports').insert({school_id:schoolId,requested_by:user.id,export_type:'school',status:'queued'});setNotice(error?error.message:'School data export requested. An operator can process the queued job.');if(!error)load()}
 async function requestDeletion(){const {data:{user}}=await supabase.auth.getUser();const {error}=await supabase.from('deletion_requests').insert({school_id:schoolId,requested_by:user.id,request_type:'school_account',status:'requested',reason:'Requested from Data & Privacy'});setNotice(error?error.message:'Deletion request recorded for review.');if(!error)load()}
 return <AppShell active="Data & privacy" schoolName={school?.name} role={role}><div className="app-page-head"><div><h1>Data & privacy</h1><p>Operational controls for exports, deletion requests, retention and consent.</p></div></div>{notice&&<div className="notice">{notice}</div>}<div className="app-head-actions"><button className="app-button" onClick={requestExport}>Request school export</button><button className="app-button danger" onClick={requestDeletion}>Request deletion</button></div><div className="app-content-grid" style={{marginTop:14}}><section className="app-panel"><div className="app-panel-head"><h2>Retention rules</h2><span>{retention.length}</span></div>{retention.map(x=><div className="data-row" key={x.id}><div><strong>{x.data_type}</strong><small>{x.legal_basis||'School policy'}</small></div><span>{x.retention_days} days</span></div>)}</section><section className="app-panel"><div className="app-panel-head"><h2>Exports</h2><span>{exports.length}</span></div>{exports.map(x=><div className="data-row" key={x.id}><div><strong>{x.export_type||'school'}</strong><small>{x.status}</small></div><span>{x.created_at?new Date(x.created_at).toLocaleString():''}</span></div>)}</section><section className="app-panel"><div className="app-panel-head"><h2>Deletion requests</h2><span>{deletions.length}</span></div>{deletions.map(x=><div className="data-row" key={x.id}><div><strong>{x.request_type}</strong><small>{x.status}</small></div><span>{x.created_at?new Date(x.created_at).toLocaleString():''}</span></div>)}</section><section className="app-panel"><div className="app-panel-head"><h2>Consent records</h2><span>{consents.length}</span></div>{consents.map(x=><div className="data-row" key={x.id}><div><strong>{x.consent_type||'Consent'}</strong><small>{x.status||'recorded'}</small></div><span>{x.created_at?new Date(x.created_at).toLocaleString():''}</span></div>)}</section></div></AppShell>}
