"use client";
import {useEffect,useState} from 'react';
import AppShell from '../../components/AppShell';
import {LoadingState,ErrorState,EmptyState} from '../../components/DataStates';
import {useSchoolContext} from '../../lib/useSchoolContext';

export default function CBT(){
 const {supabase,school,schoolId,role,loading,error,reload}=useSchoolContext();
 const [exams,setExams]=useState([]),[classes,setClasses]=useState([]),[subjects,setSubjects]=useState([]),[questions,setQuestions]=useState([]),[selected,setSelected]=useState(''),[showExam,setShowExam]=useState(false),[showQ,setShowQ]=useState(false),[exam,setExam]=useState({title:'',duration_minutes:30,class_id:'',subject_id:'',starts_at:'',ends_at:''}),[q,setQ]=useState({question_text:'',options:['','','',''],correct_answer:'',points:1}),[notice,setNotice]=useState(''),[saving,setSaving]=useState(false);
 async function load(){if(!supabase||!schoolId)return;const [e,c,s]=await Promise.all([supabase.from('cbt_exams').select('*,classes(name),subjects(name)').eq('school_id',schoolId).order('created_at',{ascending:false}),supabase.from('classes').select('*').eq('school_id',schoolId).order('name'),supabase.from('subjects').select('*').eq('school_id',schoolId).order('name')]);for(const x of [e,c,s])if(x.error)throw x.error;setExams(e.data||[]);setClasses(c.data||[]);setSubjects(s.data||[])}
 useEffect(()=>{load().catch(e=>setNotice(e.message))},[supabase,schoolId]);
 async function createExam(e){e.preventDefault();setSaving(true);try{const {error}=await supabase.from('cbt_exams').insert({...exam,school_id:schoolId,duration_minutes:Number(exam.duration_minutes),status:'draft'});if(error)throw error;setShowExam(false);await load()}catch(e){setNotice(e.message)}finally{setSaving(false)}}
 async function selectExam(id){setSelected(id);const {data,error}=await supabase.from('cbt_questions').select('*').eq('school_id',schoolId).eq('exam_id',id).order('position');if(error)setNotice(error.message);else setQuestions(data||[])}
 async function addQuestion(e){e.preventDefault();setSaving(true);try{const {error}=await supabase.from('cbt_questions').insert({school_id:schoolId,exam_id:selected,question_text:q.question_text,options:q.options.filter(Boolean),correct_answer:q.correct_answer,points:Number(q.points),position:questions.length+1});if(error)throw error;setQ({question_text:'',options:['','','',''],correct_answer:'',points:1});setShowQ(false);await selectExam(selected)}catch(e){setNotice(e.message)}finally{setSaving(false)}}
 async function publish(){const {error}=await supabase.from('cbt_exams').update({status:'scheduled'}).eq('id',selected).eq('school_id',schoolId);if(error)setNotice(error.message);else {setNotice('Exam scheduled.');await load()}}
 if(loading)return <LoadingState label="Loading CBT…"/>;if(error)return <ErrorState message={error} onRetry={reload}/>;
 return <AppShell active="CBT" schoolName={school?.name} role={role}><div className="app-page-head"><div><h1>Computer-based testing</h1><p>Create exams, build question banks and manage scheduled assessments.</p></div><button className="app-button primary" onClick={()=>setShowExam(!showExam)}>Create exam</button></div>{notice&&<div className="notice">{notice}</div>}
 <div className="app-content-grid"><div className="app-panel"><div className="app-panel-head"><h2>Exam library</h2><span>{exams.length} exams</span></div><div className="stack-list">{exams.length?exams.map(e=><button className={`list-select ${selected===e.id?'selected':''}`} key={e.id} onClick={()=>selectExam(e.id)}><span><strong>{e.title}</strong><small>{e.classes?.name||'Class'} · {e.subjects?.name||'Subject'} · {e.duration_minutes} min</small></span><b className={`status ${e.status==='scheduled'?'good':'warn'}`}>{e.status}</b></button>):<EmptyState title="No CBT exams" description="Create an exam and add questions to begin."/>}</div></div><div className="app-panel"><div className="app-panel-head"><h2>Question bank</h2><div>{selected&&<><button className="app-button" onClick={()=>setShowQ(!showQ)}>Add question</button><button className="app-button primary" onClick={publish}>Schedule exam</button></>}</div></div>{selected?<div className="question-list">{questions.length?questions.map((x,i)=><div className="question-card" key={x.id}><span className="question-number">{i+1}</span><div><strong>{x.question_text}</strong><small>{x.points} point{x.points===1?'':'s'} · Answer: {x.correct_answer}</small><div className="question-options">{(x.options||[]).map(o=><span key={o}>{o}</span>)}</div></div></div>):<EmptyState title="No questions yet" description="Add multiple-choice questions to this exam."/>}</div>:<EmptyState title="Select an exam" description="Choose an exam to manage its question bank."/>}</div></div>
 {showExam&&<div className="app-panel" style={{marginTop:14}}><div className="app-panel-head"><h2>Create CBT exam</h2><span>Draft until scheduled</span></div><form onSubmit={createExam} className="data-form"><div className="form-label"><label>Title</label><input required value={exam.title} onChange={e=>setExam({...exam,title:e.target.value})}/></div><div className="form-label"><label>Duration (minutes)</label><input type="number" min="1" value={exam.duration_minutes} onChange={e=>setExam({...exam,duration_minutes:e.target.value})}/></div><div className="form-label"><label>Class</label><select required value={exam.class_id} onChange={e=>setExam({...exam,class_id:e.target.value})}><option value="">Select class</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="form-label"><label>Subject</label><select value={exam.subject_id} onChange={e=>setExam({...exam,subject_id:e.target.value})}><option value="">Select subject</option>{subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div><div className="form-actions"><button type="button" className="app-button" onClick={()=>setShowExam(false)}>Cancel</button><button className="app-button primary">Create exam</button></div></form></div>}
 {showQ&&<div className="app-panel" style={{marginTop:14}}><div className="app-panel-head"><h2>Add multiple-choice question</h2></div><form onSubmit={addQuestion} className="data-form"><div className="form-label full"><label>Question</label><textarea required value={q.question_text} onChange={e=>setQ({...q,question_text:e.target.value})}/></div>{q.options.map((o,i)=><div className="form-label" key={i}><label>Option {String.fromCharCode(65+i)}</label><input value={o} onChange={e=>{const a=[...q.options];a[i]=e.target.value;setQ({...q,options:a})}}/></div>)}<div className="form-label"><label>Correct answer</label><input required value={q.correct_answer} onChange={e=>setQ({...q,correct_answer:e.target.value})}/></div><div className="form-label"><label>Points</label><input type="number" min="1" value={q.points} onChange={e=>setQ({...q,points:e.target.value})}/></div><div className="form-actions"><button type="button" className="app-button" onClick={()=>setShowQ(false)}>Cancel</button><button className="app-button primary" disabled={saving}>{saving?'Saving…':'Save question'}</button></div></form></div>}
 </AppShell>
}
