"use client";
import {useEffect,useState} from 'react';
import AppShell from '../../components/AppShell';
import {LoadingState,ErrorState} from '../../components/DataStates';
import {useSchoolContext} from '../../lib/useSchoolContext';

export default function Settings(){
 const {supabase,school,schoolId,role,loading,error,reload}=useSchoolContext();
 const [schoolForm,setSchoolForm]=useState({name:'',timezone:'Africa/Lagos',currency:'NGN'});
 const [web,setWeb]=useState({headline:'',subheadline:'',primary_color:'#3882F6',accent_color:'#A3E635',contact_email:'',contact_phone:'',address:'',is_published:false});
 const [pages,setPages]=useState([]),[sessions,setSessions]=useState([]),[terms,setTerms]=useState([]),[subjects,setSubjects]=useState([]),[scales,setScales]=useState([]);
 const [sessionName,setSessionName]=useState(''),[termName,setTermName]=useState(''),[subjectName,setSubjectName]=useState(''),[scaleName,setScaleName]=useState('');
 const [notice,setNotice]=useState(''),[saving,setSaving]=useState(false),[logo,setLogo]=useState(null),[heroImage,setHeroImage]=useState(null);
 async function load(){
  if(!supabase||!schoolId)return;
  const [w,p,s,t,sub,g]=await Promise.all([
   supabase.from('website_settings').select('*').eq('school_id',schoolId).maybeSingle(),
   supabase.from('website_pages').select('*').eq('school_id',schoolId).order('title'),
   supabase.from('academic_sessions').select('*').eq('school_id',schoolId).order('starts_on',{ascending:false}),
   supabase.from('academic_terms').select('*').eq('school_id',schoolId).order('starts_on'),
   supabase.from('subjects').select('*').eq('school_id',schoolId).order('name'),
   supabase.from('grading_scales').select('*,grading_scale_items(*)').eq('school_id',schoolId).order('name')
  ]);
  for(const r of [w,p,s,t,sub,g])if(r.error)throw r.error;
  setPages(p.data||[]);setSchoolForm({name:school?.name||'',timezone:school?.timezone||'Africa/Lagos',currency:school?.currency||'NGN'});if(w.data)setWeb(w.data);setSessions(s.data||[]);setTerms(t.data||[]);setSubjects(sub.data||[]);setScales(g.data||[]);
 }
 useEffect(()=>{if(school)load().catch(e=>setNotice(e.message))},[supabase,schoolId,school]);
 async function uploadLogo(){if(!logo)return;setSaving(true);try{const ext=logo.name.split('.').pop()||'png';const path=`${schoolId}/logo.${ext}`;const up=await supabase.storage.from('school-branding').upload(path,logo,{upsert:true,contentType:logo.type});if(up.error)throw up.error;const u=await supabase.from('schools').update({logo_path:path}).eq('id',schoolId);if(u.error)throw u.error;setNotice('School logo uploaded.');setLogo(null)}catch(e){setNotice(e.message)}finally{setSaving(false)}}
 async function uploadHero(){if(!heroImage)return;setSaving(true);try{const ext=heroImage.name.split('.').pop()||'jpg';const path=`${schoolId}/hero.${ext}`;const up=await supabase.storage.from('school-branding').upload(path,heroImage,{upsert:true,contentType:heroImage.type});if(up.error)throw up.error;setWeb(x=>({...x,hero_image_path:path}));const {error}=await supabase.from('website_settings').upsert({...web,school_id:schoolId,hero_image_path:path});if(error)throw error;setHeroImage(null);setNotice('Website hero image uploaded.')}catch(e){setNotice(e.message)}finally{setSaving(false)}}
 async function saveIdentity(e){e.preventDefault();setSaving(true);try{const a=await supabase.from('schools').update({name:schoolForm.name.trim(),timezone:schoolForm.timezone.trim(),currency:schoolForm.currency.trim().toUpperCase()}).eq('id',schoolId);if(a.error)throw a.error;const b=await supabase.from('website_settings').upsert({...web,school_id:schoolId});if(b.error)throw b.error;setNotice('School identity and website settings saved.');await reload()}catch(e){setNotice(e.message)}finally{setSaving(false)}}
 async function add(table,name,setter){if(!name.trim())return;const payload={school_id:schoolId,name:name.trim()};if(table==='academic_terms')payload.session_id=sessions.find(x=>x.is_current)?.id||sessions[0]?.id;if(table==='academic_terms'&&!payload.session_id){setNotice('Create an academic session before adding a term.');return}const {error}=await supabase.from(table).insert(payload);if(error)setNotice(error.message);else{setter('');await load()}}
 async function toggleCurrent(table,id){const {error}=await supabase.from(table).update({is_current:false}).eq('school_id',schoolId);if(error){setNotice(error.message);return}const r=await supabase.from(table).update({is_current:true}).eq('id',id).eq('school_id',schoolId);if(r.error)setNotice(r.error.message);else load()}
 async function addScale(){if(!scaleName.trim())return;const {error}=await supabase.from('grading_scales').insert({school_id:schoolId,name:scaleName.trim(),is_default:scales.length===0});if(error)setNotice(error.message);else{setScaleName('');await load()}}
 async function savePage(page){const {error}=await supabase.from('website_pages').upsert({...page,school_id:schoolId});if(error)setNotice(error.message);else{setNotice('Website page saved.');load()}}
 if(loading)return <LoadingState label="Loading settings…"/>;if(error)return <ErrorState message={error} onRetry={reload}/>;
 return <AppShell active="Settings" schoolName={school?.name} role={role}>
  <div className="app-page-head"><div><h1>School settings</h1><p>Manage identity, academic structure, grading, public website and school configuration.</p></div></div>
  {notice&&<div className="notice">{notice}</div>}
  <div className="app-content-grid">
   <div className="app-panel"><div className="app-panel-head"><h2>School identity</h2><span>Admin controlled</span></div><form onSubmit={saveIdentity} className="data-form">
    <div className="form-label full"><label>School logo</label><input type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" onChange={e=>setLogo(e.target.files?.[0]||null)}/><div className="form-actions" style={{justifyContent:'flex-start'}}><button type="button" className="app-button" onClick={uploadLogo} disabled={!logo||saving}>{saving?'Uploading…':'Upload logo'}</button></div></div>
    <div className="form-label"><label>School name</label><input required value={schoolForm.name} onChange={e=>setSchoolForm({...schoolForm,name:e.target.value})}/></div><div className="form-label"><label>Timezone</label><input value={schoolForm.timezone} onChange={e=>setSchoolForm({...schoolForm,timezone:e.target.value})}/></div><div className="form-label"><label>Currency</label><input maxLength="3" value={schoolForm.currency} onChange={e=>setSchoolForm({...schoolForm,currency:e.target.value})}/></div>
    <div className="form-label"><label>Primary color</label><input value={web.primary_color} onChange={e=>setWeb({...web,primary_color:e.target.value})}/></div><div className="form-label"><label>Accent color</label><input value={web.accent_color} onChange={e=>setWeb({...web,accent_color:e.target.value})}/></div><div className="form-label full"><label>Website hero image</label><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>setHeroImage(e.target.files?.[0]||null)}/><div className="form-actions" style={{justifyContent:'flex-start'}}><button type="button" className="app-button" onClick={uploadHero} disabled={!heroImage||saving}>{saving?'Uploading…':'Upload hero image'}</button></div></div><div className="form-label full"><label>Website headline</label><input value={web.headline||''} onChange={e=>setWeb({...web,headline:e.target.value})}/></div><div className="form-label full"><label>Website subheadline</label><textarea value={web.subheadline||''} onChange={e=>setWeb({...web,subheadline:e.target.value})}/></div><div className="form-label"><label>Contact email</label><input type="email" value={web.contact_email||''} onChange={e=>setWeb({...web,contact_email:e.target.value})}/></div><div className="form-label"><label>Contact phone</label><input value={web.contact_phone||''} onChange={e=>setWeb({...web,contact_phone:e.target.value})}/></div><div className="form-label full"><label>Address</label><input value={web.address||''} onChange={e=>setWeb({...web,address:e.target.value})}/></div><div className="form-label"><label>Publish website</label><select value={web.is_published?'yes':'no'} onChange={e=>setWeb({...web,is_published:e.target.value==='yes'})}><option value="no">Draft</option><option value="yes">Published</option></select></div><div className="form-actions"><button className="app-button primary" disabled={saving}>{saving?'Saving…':'Save settings'}</button></div>
   </form></div>
   <div className="app-panel"><div className="app-panel-head"><h2>Academic sessions</h2><span>{sessions.length}</span></div><div className="inline-add"><input placeholder="e.g. 2026/2027" value={sessionName} onChange={e=>setSessionName(e.target.value)}/><button className="app-button" onClick={()=>add('academic_sessions',sessionName,setSessionName)}>Add</button></div><div className="stack-list">{sessions.map(s=><div className="list-select" key={s.id}><span><strong>{s.name}</strong><small>{s.is_current?'Current session':'Not current'}</small></span><button className="app-button" onClick={()=>toggleCurrent('academic_sessions',s.id)}>{s.is_current?'Current':'Set current'}</button></div>)}</div></div>
  </div>
  <div className="app-content-grid" style={{marginTop:14}}><div className="app-panel"><div className="app-panel-head"><h2>Terms</h2><span>{terms.length}</span></div><div className="inline-add"><input placeholder="e.g. First Term" value={termName} onChange={e=>setTermName(e.target.value)}/><button className="app-button" onClick={()=>add('academic_terms',termName,setTermName)}>Add</button></div><div className="stack-list">{terms.map(t=><div className="list-select" key={t.id}><span><strong>{t.name}</strong><small>{t.is_current?'Current term':'Not current'}</small></span><button className="app-button" onClick={()=>toggleCurrent('academic_terms',t.id)}>{t.is_current?'Current':'Set current'}</button></div>)}</div></div><div className="app-panel"><div className="app-panel-head"><h2>Subjects</h2><span>{subjects.length}</span></div><div className="inline-add"><input placeholder="e.g. Mathematics" value={subjectName} onChange={e=>setSubjectName(e.target.value)}/><button className="app-button" onClick={()=>add('subjects',subjectName,setSubjectName)}>Add</button></div><div className="tag-list">{subjects.map(s=><span className="tag" key={s.id}>{s.name}</span>)}</div></div></div>
  <div className="app-panel" style={{marginTop:14}}><div className="app-panel-head"><h2>Grading scales</h2><span>{scales.length} scales</span></div><div className="inline-add"><input placeholder="e.g. Junior secondary scale" value={scaleName} onChange={e=>setScaleName(e.target.value)}/><button className="app-button" onClick={addScale}>Add scale</button></div><div className="stack-list">{scales.map(g=><div className="list-select" key={g.id}><span><strong>{g.name}</strong><small>{g.is_default?'Default scale':'Custom scale'} · {(g.grading_scale_items||[]).length} grades</small></span><span className="status good">{g.is_default?'Default':'Available'}</span></div>)}</div></div>
  <div className="app-panel" style={{marginTop:14}}><div className="app-panel-head"><h2>Public website pages</h2><span>{pages.length} pages</span></div><div className="stack-list">{pages.map(p=><div className="website-page-editor" key={p.id}><div className="form-label"><label>Title</label><input value={p.title} onChange={e=>setPages(pages.map(x=>x.id===p.id?{...x,title:e.target.value}:x))}/></div><div className="form-label full"><label>Body</label><textarea value={p.body} onChange={e=>setPages(pages.map(x=>x.id===p.id?{...x,body:e.target.value}:x))}/></div><div className="form-actions"><button className="app-button primary" onClick={()=>savePage(p)}>Save page</button></div></div>)}</div></div>
 </AppShell>
}
