"use client";
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {useParams,useRouter} from 'next/navigation';
import {getCurrentContext} from '../../../../lib/school';

export default function TakeExam(){
 const {examId}=useParams(); const router=useRouter();
 const [ctx,setCtx]=useState(null),[exam,setExam]=useState(null),[questions,setQuestions]=useState([]),[answers,setAnswers]=useState({}),[attempt,setAttempt]=useState(null),[remaining,setRemaining]=useState(0),[index,setIndex]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(''),[saving,setSaving]=useState(false),[syncing,setSyncing]=useState(false),[submitted,setSubmitted]=useState(false),[fullscreen,setFullscreen]=useState(false),[online,setOnline]=useState(true),[flagged,setFlagged]=useState({}),[integrity,setIntegrity]=useState(0);
 const submitting=useRef(false);
 const queueKey=attempt?`edvora-cbt-${attempt}`:null;
 const requestFullscreen=useCallback(async()=>{try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();}catch{}},[]);
 const recordEvent=useCallback(async(type,metadata={})=>{if(!ctx?.supabase||!attempt)return;await ctx.supabase.rpc('record_cbt_integrity_event',{target_attempt:attempt,target_event:type,target_metadata:metadata}).then(({error})=>{if(!error)setIntegrity(v=>v+1)});},[ctx,attempt]);
 const syncQueue=useCallback(async()=>{if(!ctx?.supabase||!attempt||!queueKey)return;const queue=JSON.parse(localStorage.getItem(queueKey)||'[]');if(!queue.length)return;setSyncing(true);const remainingItems=[];for(const item of queue){const {error}=await ctx.supabase.rpc('save_student_cbt_answer',item);if(error)remainingItems.push(item)}if(remainingItems.length)localStorage.setItem(queueKey,JSON.stringify(remainingItems));else localStorage.removeItem(queueKey);setSyncing(false);},[ctx,attempt,queueKey]);
 useEffect(()=>{(async()=>{try{const c=await getCurrentContext();setCtx(c);const {data,error}=await c.supabase.rpc('get_student_cbt_exam',{target_exam_id:examId});if(error)throw error;setExam(data.exam);setQuestions(data.questions||[]);setOnline(navigator.onLine);}catch(e){setError(e.message||'Unable to open this exam.')}finally{setLoading(false)}})()},[examId]);
 async function startAttempt(){if(!ctx||attempt)return;setSaving(true);setError('');try{if(exam?.require_fullscreen&&!document.fullscreenElement)await requestFullscreen();if(exam?.require_fullscreen&&!document.fullscreenElement)throw new Error('Fullscreen is required before the exam can start.');const {data:aid,error:ae}=await ctx.supabase.rpc('start_student_cbt_attempt',{target_exam_id:examId});if(ae)throw ae;const {data:row,error:re}=await ctx.supabase.from('cbt_attempts').select('id,started_at,server_expires_at,status').eq('id',aid).single();if(re)throw re;if(row.status!=='in_progress')throw new Error('This exam attempt is not active.');setAttempt(row.id);const end=new Date(row.server_expires_at).getTime();setRemaining(Math.max(0,Math.floor((end-Date.now())/1000)));}catch(e){setError(e.message||'Unable to start this exam.')}finally{setSaving(false)}}
 useEffect(()=>{const fs=()=>setFullscreen(Boolean(document.fullscreenElement));const vis=()=>{if(document.hidden)recordEvent('visibility_hidden');};const onlineH=()=>{setOnline(true);recordEvent('online');syncQueue()};const offlineH=()=>{setOnline(false);recordEvent('offline')};document.addEventListener('fullscreenchange',fs);document.addEventListener('visibilitychange',vis);window.addEventListener('online',onlineH);window.addEventListener('offline',offlineH);return()=>{document.removeEventListener('fullscreenchange',fs);document.removeEventListener('visibilitychange',vis);window.removeEventListener('online',onlineH);window.removeEventListener('offline',offlineH)}},[recordEvent,syncQueue]);
 useEffect(()=>{if(!exam?.require_fullscreen)return;const onFs=()=>{if(!document.fullscreenElement&&!submitted)recordEvent('fullscreen_exit')};document.addEventListener('fullscreenchange',onFs);return()=>document.removeEventListener('fullscreenchange',onFs)},[exam,submitted,recordEvent]);
 useEffect(()=>{if(!attempt||submitted)return;const t=setInterval(()=>setRemaining(v=>{if(v<=1){clearInterval(t);submit();return 0}return v-1}),1000);const server=setInterval(async()=>{try{const {data}=await ctx?.supabase.from('cbt_attempts').select('status,server_expires_at').eq('id',attempt).single();if(data?.status!=='in_progress'){clearInterval(server);if(data?.status==='expired')setError('The server has ended this exam attempt.');}}catch{}},15000);return()=>{clearInterval(t);clearInterval(server)}},[attempt,submitted,ctx]);
 useEffect(()=>{const t=setInterval(syncQueue,5000);return()=>clearInterval(t)},[syncQueue]);
 const current=questions[index]; const time=useMemo(()=>`${String(Math.floor(remaining/60)).padStart(2,'0')}:${String(remaining%60).padStart(2,'0')}`,[remaining]);
 async function choose(value){if(!current||!attempt||saving)return;setAnswers(a=>({...a,[current.id]:value}));const payload={target_attempt_id:attempt,target_question_id:current.id,target_answer:typeof value==='string'?value:JSON.stringify(value)};setSaving(true);try{if(!online)throw new Error('offline');const {error}=await ctx.supabase.rpc('save_student_cbt_answer',payload);if(error)throw error;}catch{const queue=JSON.parse(localStorage.getItem(queueKey)||'[]').filter(x=>x.target_question_id!==payload.target_question_id);queue.push(payload);localStorage.setItem(queueKey,JSON.stringify(queue));}finally{setSaving(false)}}
 async function submit(){if(!attempt||submitting.current)return;submitting.current=true;setSaving(true);await syncQueue();try{const {error}=await ctx.supabase.rpc('submit_student_cbt_attempt',{target_attempt_id:attempt});if(error)throw error;setSubmitted(true);if(document.fullscreenElement)await document.exitFullscreen().catch(()=>{});}catch(e){setError(e.message||'We could not submit the exam. Your saved answers remain on this device.');submitting.current=false;}finally{setSaving(false)}}
 if(loading)return <div className="cbt-screen"><div className="cbt-loading">Opening exam…</div></div>;
 if(error)return <div className="cbt-screen"><div className="cbt-block"><h1>Exam unavailable</h1><p>{error}</p><button onClick={()=>router.push('/student/cbt')}>Back to exams</button></div></div>;
 if(!attempt&&!submitted)return <div className="cbt-screen"><div className="cbt-block"><div className="cbt-brand">EDVORA CBT</div><h1>Enter fullscreen to begin</h1><p>This exam uses a focused fullscreen workspace. Your normal Edvora navigation is unavailable during the attempt.</p><button className="cbt-primary" disabled={saving} onClick={startAttempt}>{saving?'Starting…':exam?.require_fullscreen?'Enter fullscreen & start':'Start exam'}</button><button className="cbt-secondary" onClick={()=>router.push('/student/cbt')}>Exit exam</button></div></div>;
 if(submitted)return <div className="cbt-screen"><div className="cbt-block"><div className="cbt-brand">EDVORA CBT</div><h1>Exam submitted successfully.</h1><p>Your result will be available when your school publishes it.</p><button className="cbt-primary" onClick={()=>router.push('/student/cbt')}>Back to exams</button></div></div>;
 return <div className="cbt-screen" onContextMenu={e=>e.preventDefault()}><header className="cbt-header"><div><span className="cbt-brand">EDVORA CBT</span><strong>{exam.title}</strong><small>{exam.subject?.name||'Examination'}</small></div><div className="cbt-header-right"><span className={online?'cbt-saved':'cbt-offline'}>{syncing?'Syncing…':online?'Saved':'Offline — saved locally'}</span><strong className={remaining<60?'cbt-time danger':''}>{time}</strong></div></header><main className="cbt-main"><aside className="cbt-nav"><div className="cbt-nav-title">Questions</div>{questions.map((q,i)=><button key={q.id} className={`cbt-q ${i===index?'current':''} ${answers[q.id]!==undefined?'answered':''} ${flagged[q.id]?'flagged':''}`} onClick={()=>setIndex(i)} aria-label={`Question ${i+1}${answers[q.id]!==undefined?', answered':''}${flagged[q.id]?', flagged':''}`}>{i+1}</button>)}</aside><section className="cbt-question"><div className="cbt-question-top"><span>Question {index+1} of {questions.length}</span><button className={flagged[current?.id]?'cbt-flag active':'cbt-flag'} onClick={()=>setFlagged(x=>({...x,[current.id]:!x[current.id]}))}>{flagged[current?.id]?'Flagged':'Flag question'}</button></div><h1>{current?.question_text}</h1>{current?.question_type==='true_false'?<div className="cbt-options">{['True','False'].map(v=><button key={v} className={answers[current.id]===v?'selected':''} onClick={()=>choose(v)}>{v}</button>)}</div>:<div className="cbt-options">{(current?.options||[]).map((o,i)=><button key={i} className={answers[current.id]===o?'selected':''} onClick={()=>choose(o)}>{String.fromCharCode(65+i)} <span>{o}</span></button>)}</div>}<div className="cbt-footer"><button className="cbt-secondary" disabled={index===0} onClick={()=>setIndex(i=>i-1)}>Previous</button>{index<questions.length-1?<button className="cbt-primary" onClick={()=>setIndex(i=>i+1)}>Next</button>:<button className="cbt-primary" disabled={saving} onClick={submit}>{saving?'Submitting…':'Submit exam'}</button>}</div></section></main></div>
}
