"use client";
import {useEffect,useState} from 'react';
import AppShell from '../../components/AppShell';
import {LoadingState,ErrorState,EmptyState} from '../../components/DataStates';
import {useSchoolContext} from '../../lib/useSchoolContext';

export default function Attendance(){
 const {supabase,school,schoolId,role,loading,error,reload}=useSchoolContext();
 const [classes,setClasses]=useState([]),[students,setStudents]=useState([]),[selected,setSelected]=useState(''),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[records,setRecords]=useState({}),[saving,setSaving]=useState(false),[notice,setNotice]=useState('');
 async function loadClasses(){if(!supabase||!schoolId)return;const {data,error}=await supabase.from('classes').select('*').eq('school_id',schoolId).order('name');if(error)throw error;setClasses(data||[]);if(!selected&&data?.[0])setSelected(data[0].id)}
 async function loadRoster(){if(!supabase||!schoolId||!selected)return;const [s,a]=await Promise.all([supabase.from('students').select('*').eq('school_id',schoolId).eq('class_id',selected).eq('status','active').order('first_name'),supabase.from('attendance_records').select('*').eq('school_id',schoolId).eq('class_id',selected).eq('attendance_date',date)]);if(s.error)throw s.error;if(a.error)throw a.error;setStudents(s.data||[]);const map={};(a.data||[]).forEach(r=>map[r.student_id]=r.status);const next={};(s.data||[]).forEach(st=>next[st.id]=map[st.id]||'present');setRecords(next)}
 useEffect(()=>{loadClasses().catch(e=>setNotice(e.message))},[supabase,schoolId]);useEffect(()=>{loadRoster().catch(e=>setNotice(e.message))},[supabase,schoolId,selected,date]);
 async function save(){setSaving(true);setNotice('');try{const payload=students.map(s=>({school_id:schoolId,student_id:s.id,class_id:selected,attendance_date:date,status:records[s.id]||'present'}));const {error}=await supabase.from('attendance_records').upsert(payload,{onConflict:'school_id,student_id,attendance_date'});if(error)throw error;setNotice(`Attendance saved for ${students.length} students.`)}catch(e){setNotice(e.message)}finally{setSaving(false)}}
 if(loading)return <LoadingState label="Loading attendance…"/>;if(error)return <ErrorState message={error} onRetry={reload}/>;
 const counts=Object.values(records).reduce((a,v)=>(a[v]=(a[v]||0)+1,a),{});
 return <AppShell active="Attendance" schoolName={school?.name} role={role}><div className="app-page-head"><div><h1>Attendance</h1><p>Take daily attendance by class and keep a complete attendance history.</p></div><button className="app-button primary" onClick={save} disabled={!students.length||saving}>{saving?'Saving…':'Save attendance'}</button></div>{notice&&<div className="notice">{notice}</div>}<div className="app-grid-4"><div className="app-stat"><small>Present</small><strong>{counts.present||0}</strong><em>Today</em></div><div className="app-stat"><small>Absent</small><strong>{counts.absent||0}</strong><em>Follow up</em></div><div className="app-stat"><small>Late</small><strong>{counts.late||0}</strong><em>Recorded</em></div><div className="app-stat"><small>Excused</small><strong>{counts.excused||0}</strong><em>Approved</em></div></div><div className="app-panel" style={{marginTop:14}}><div className="app-panel-head"><h2>Daily register</h2><div className="inline-filters"><select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Select class</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></div></div>{students.length?<div className="attendance-list">{students.map(s=><div className="attendance-row" key={s.id}><div><strong>{s.first_name} {s.last_name}</strong><small>{s.admission_number||'No admission number'}</small></div><div className="attendance-actions">{['present','absent','late','excused'].map(v=><button key={v} className={records[s.id]===v?'selected':''} onClick={()=>setRecords({...records,[s.id]:v})}>{v}</button>)}</div></div>)}</div>:<EmptyState title="No students in this class" description="Choose another class or add students to this class before taking attendance."/>}</div></AppShell>
}
