"use client";
import {useEffect,useState} from 'react';
import AppShell from '../../components/AppShell';
import {Icon} from '../../components/Brand';
import {LoadingState,ErrorState,EmptyState} from '../../components/DataStates';
import {useSchoolContext} from '../../lib/useSchoolContext';

export default function Students(){
 const {supabase,school,schoolId,role,loading,error,reload}=useSchoolContext();
 const [classes,setClasses]=useState([]),[students,setStudents]=useState([]),[links,setLinks]=useState({}),[form,setForm]=useState({first_name:'',last_name:'',gender:'',class_id:'',date_of_birth:''}),[show,setShow]=useState(false),[portalStudent,setPortalStudent]=useState(null),[portal,setPortal]=useState({email:'',full_name:'',relationship:'Parent',type:'parent'}),[errorMsg,setErrorMsg]=useState(''),[saving,setSaving]=useState(false),[copied,setCopied]=useState('');
 async function load(){try{if(!supabase||!schoolId)return;const [st,cl,pl]=await Promise.all([supabase.from('students').select('*').eq('school_id',schoolId).order('created_at',{ascending:false}),supabase.from('classes').select('*').eq('school_id',schoolId).order('name'),supabase.from('student_parent_link_codes').select('student_id,last_four,rotated_at').eq('school_id',schoolId)]);for(const r of [st,cl,pl])if(r.error)throw r.error;setClasses(cl.data||[]);setStudents(st.data||[]);setLinks(Object.fromEntries((pl.data||[]).map(x=>[x.student_id,x])))}catch(err){setErrorMsg(err?.message||'Unable to load students.')}}
 useEffect(()=>{load()},[supabase,schoolId]);
 async function add(e){e.preventDefault();setErrorMsg('');setSaving(true);try{const r=await fetch('/api/students',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,school_id:schoolId})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'We could not save this student.');setForm({first_name:'',last_name:'',gender:'',class_id:'',date_of_birth:''});setShow(false);setErrorMsg(`Student created. Admission number: ${j.student?.admission_number||'generated automatically'}`);await load()}catch(err){setErrorMsg(err?.message||'We could not save this student.')}finally{setSaving(false)}}
 async function rotate(studentId){setSaving(true);try{const {data,error}=await supabase.rpc('rotate_parent_link_code',{target_student_id:studentId});if(error)throw error;setLinks(x=>({...x,[studentId]:{...x[studentId],code:data,last_four:String(data).slice(-4)}}));setCopied(studentId);await navigator.clipboard?.writeText(data);setTimeout(()=>setCopied(''),1800)}catch(e){setErrorMsg(e.message)}finally{setSaving(false)}}
 async function copy(code,id){try{await navigator.clipboard.writeText(code);setCopied(id);setTimeout(()=>setCopied(''),1600)}catch{setErrorMsg('Copy failed. Select the Parent ID manually.')}}
 async function sendPortal(e){e.preventDefault();setSaving(true);setErrorMsg('');try{const r=await fetch('/api/portal-invitations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...portal,student_id:portalStudent.id,school_id:schoolId})});const j=await r.json();if(!r.ok)throw new Error(j.error);setPortalStudent(null);setPortal({email:'',full_name:'',relationship:'Parent',type:'parent'});setErrorMsg('Portal invitation sent to '+j.email)}catch(err){setErrorMsg(err.message)}finally{setSaving(false)}}
 if(loading)return <LoadingState label="Loading students…"/>;if(error)return <ErrorState message={error} onRetry={reload}/>;
 return <AppShell active="Students" schoolName={school?.name} role={role}><div className="app-page-head"><div><h1>Students</h1><p>Manage the student register and secure parent linking.</p></div><div className="app-head-actions"><button className="app-button" onClick={()=>setPortalStudent(students[0]||null)} disabled={!students.length}>Invite portal</button><button className="app-button primary" onClick={()=>setShow(!show)}><Icon name="plus" size={15}/> Add student</button></div></div>
 {errorMsg&&<div className="notice">{errorMsg}</div>}
 {show&&<div className="app-panel" style={{marginBottom:14}}><div className="app-panel-head"><h2>Add student</h2><span>Admission number and Parent ID are generated automatically</span></div><form onSubmit={add} className="data-form"><div className="form-label"><label>First name</label><input required value={form.first_name} onChange={e=>setForm({...form,first_name:e.target.value})}/></div><div className="form-label"><label>Last name</label><input required value={form.last_name} onChange={e=>setForm({...form,last_name:e.target.value})}/></div><div className="form-label"><label>Date of birth</label><input type="date" value={form.date_of_birth} onChange={e=>setForm({...form,date_of_birth:e.target.value})}/></div><div className="form-label"><label>Class</label><select value={form.class_id} onChange={e=>setForm({...form,class_id:e.target.value})}><option value="">Select class</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="form-label"><label>Gender</label><select value={form.gender} onChange={e=>setForm({...form,gender:e.target.value})}><option value="">Select</option><option>Male</option><option>Female</option></select></div><div className="form-actions"><button type="button" className="app-button" onClick={()=>setShow(false)}>Cancel</button><button className="app-button primary" disabled={saving}>{saving?'Saving…':'Save student'}</button></div></form></div>}
 <div className="app-panel"><div className="app-panel-head"><h2>Student register</h2><span>{students.length} students · Parent IDs are school-scoped secrets</span></div><div className="app-table-wrap"><table className="app-table"><thead><tr><th>Name</th><th>Admission no.</th><th>Class</th><th>Status</th><th>Parent ID</th><th>Actions</th></tr></thead><tbody>{students.length?students.map(s=>{const l=links[s.id];return <tr key={s.id}><td><a href={`/students/${s.id}`}><strong>{s.first_name} {s.last_name}</strong></a></td><td>{s.admission_number||'-'}</td><td>{classes.find(c=>c.id===s.class_id)?.name||'-'}</td><td><span className={`status ${s.status==='active'?'good':'warn'}`}>{s.status}</span></td><td>{l?.code?<div style={{display:'flex',alignItems:'center',gap:5}}><code style={{fontSize:9,background:'#f5f7fa',padding:'5px 7px',borderRadius:5}}>{l.code}</code><button className="app-button" onClick={()=>copy(l.code,s.id)}>{copied===s.id?'Copied':'Copy'}</button></div>:<span>{l?.last_four?`•••• ${l.last_four}`:'Not issued'}</span>}</td><td><div className="table-actions"><button className="app-button" onClick={()=>rotate(s.id)} disabled={saving}>{l?.last_four?'Rotate / reveal ID':'Generate Parent ID'}</button><button className="app-button primary" onClick={()=>setPortalStudent(s)}>Invite parent</button></div></td></tr>}) : <tr><td colSpan="6"><EmptyState title="No students yet" description="Add your first student. Edvora will generate a strong Parent ID automatically." action={<button className="app-button primary" onClick={()=>setShow(true)}>Add student</button>}/></td></tr>}</tbody></table></div></div>
 {portalStudent&&<div className="app-panel" style={{marginTop:14}}><div className="app-panel-head"><h2>Portal invitation</h2><span>{portalStudent.first_name} {portalStudent.last_name}</span></div><form onSubmit={sendPortal} className="data-form"><div className="form-label"><label>Portal type</label><select value={portal.type} onChange={e=>setPortal({...portal,type:e.target.value})}><option value="parent">Parent / guardian</option><option value="student">Student</option></select></div><div className="form-label"><label>Email</label><input required type="email" value={portal.email} onChange={e=>setPortal({...portal,email:e.target.value})}/></div><div className="form-label"><label>Full name</label><input value={portal.full_name} onChange={e=>setPortal({...portal,full_name:e.target.value})}/></div><div className="form-label"><label>Relationship</label><input value={portal.relationship} onChange={e=>setPortal({...portal,relationship:e.target.value})}/></div><div className="form-actions"><button type="button" className="app-button" onClick={()=>setPortalStudent(null)}>Cancel</button><button className="app-button primary" disabled={saving}>{saving?'Sending…':'Send invitation'}</button></div></form></div>}
 </AppShell>
}
