"use client";
import {useEffect,useState} from 'react';
import AppShell from '../../components/AppShell';
import {LoadingState,ErrorState,EmptyState} from '../../components/DataStates';
import {useSchoolContext} from '../../lib/useSchoolContext';

export default function Pricing(){
 const {supabase,school,schoolId,role,loading,error,reload}=useSchoolContext();const [plans,setPlans]=useState([]),[sub,setSub]=useState(null),[cycle,setCycle]=useState('monthly'),[notice,setNotice]=useState(''),[busy,setBusy]=useState(''),[cancelling,setCancelling]=useState(false);
 async function load(){if(!supabase||!schoolId)return;const [p,s]=await Promise.all([supabase.from('subscription_plans').select('*').eq('active',true).order('monthly_amount'),supabase.from('subscriptions').select('*').eq('school_id',schoolId).maybeSingle()]);if(p.error)throw p.error;if(s.error)throw s.error;setPlans(p.data||[]);setSub(s.data)}useEffect(()=>{load().catch(e=>setNotice(e.message))},[supabase,schoolId]);
 async function cancelSubscription(){setCancelling(true);try{const r=await fetch('/api/billing/paystack/cancel',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({school_id:schoolId})});const j=await r.json();if(!r.ok)throw new Error(j.error);setNotice('Subscription will cancel at the end of the current period.');await load()}catch(e){setNotice(e.message)}finally{setCancelling(false)}}
 async function checkout(code){setBusy(code);setNotice('');try{const r=await fetch('/api/billing/paystack',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({plan_code:code,cycle,school_id:schoolId})});const j=await r.json();if(!r.ok)throw new Error(j.error);window.location.assign(j.authorization_url)}catch(e){setNotice(e.message)}finally{setBusy('')}}
 if(loading)return <LoadingState label="Loading plans…"/>;if(error)return <ErrorState message={error} onRetry={reload}/>;return <AppShell active="Billing" schoolName={school?.name} role={role}><div className="app-page-head"><div><h1>Edvora billing</h1><p>Choose the subscription that matches your school's size and workflow.</p></div><div className="billing-cycle"><button className={cycle==='monthly'?'selected':''} onClick={()=>setCycle('monthly')}>Monthly</button><button className={cycle==='yearly'?'selected':''} onClick={()=>setCycle('yearly')}>Yearly</button></div></div>{notice&&<div className="notice">{notice}</div>}<div className="current-subscription"><span>Current plan</span><strong>{sub?.plan_code||'starter'}</strong><em>{sub?.status||'trialing'}</em>{sub?.cancel_at_period_end&&<span className="status warn">Cancels at period end</span>}{sub?.status==='active'&&!sub?.cancel_at_period_end&&<button className="app-button" onClick={cancelSubscription} disabled={cancelling}>{cancelling?'Saving…':'Cancel at period end'}</button>}</div><div className="pricing-grid-v2">{plans.map(p=><article className="pricing-card-v2" key={p.code}><h2>{p.name}</h2><strong>{p.monthly_amount?`₦${Number(cycle==='monthly'?p.monthly_amount:p.yearly_amount).toLocaleString()}`:'Custom'}</strong><small>{p.monthly_amount?(cycle==='monthly'?'per month':'per year'):'Talk to Edvora'}</small><ul>{(p.features||[]).map(f=><li key={f}>{f}</li>)}</ul>{p.monthly_amount?<button className="app-button primary" disabled={busy===p.code||sub?.plan_code===p.code} onClick={()=>checkout(p.code)}>{busy===p.code?'Opening checkout…':sub?.plan_code===p.code?'Current plan':'Choose plan'}</button>:<a className="app-button" href="mailto:sales@edvora.ng">Contact sales</a>}</article>)}</div></AppShell>}
